"""Shared limits for the multi-agent orchestration engine."""

from servers.agents.agent_budgets import (
    MULTI_DEFAULT_COMMAND_TIMEOUT_SEC,
    MULTI_DEFAULT_SESSION_TIMEOUT_SEC,
    MULTI_MAX_PLAN_TASKS,
    MULTI_MAX_TASK_ITERATIONS,
)

MAX_PLAN_TASKS = MULTI_MAX_PLAN_TASKS
MAX_TASK_ITERATIONS = MULTI_MAX_TASK_ITERATIONS
SESSION_TIMEOUT_DEFAULT = MULTI_DEFAULT_SESSION_TIMEOUT_SEC
DEFAULT_COMMAND_TIMEOUT = MULTI_DEFAULT_COMMAND_TIMEOUT_SEC
CONTROL_POLL_INTERVAL = 0.5
