from __future__ import annotations


PILOT_TEMPLATE_SLUGS = {
    "pilot-keycloak-access-change",
    "pilot-kubernetes-rollout",
    "pilot-gitlab-failed-pipeline-mr",
    "pilot-database-diagnostics-maintenance",
    "pilot-observability-incident-response",
    "pilot-linux-package-maintenance",
    "pilot-linux-disk-cleanup",
    "pilot-backup-restore-check",
    "pilot-service-config-validate-restart",
}


PILOT_TEMPLATE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "pilot-keycloak-access-change": (
        "keycloak",
        "keycloack",
        "kc",
        "iam",
        "identity",
        "access",
        "realm",
        "role",
        "roles",
        "group",
        "groups",
        "user",
        "users",
        "client",
        "киклок",
        "кейклок",
        "доступ",
        "роль",
        "роли",
        "групп",
        "пользовател",
    ),
    "pilot-kubernetes-rollout": (
        "kubernetes",
        "k8s",
        "kubectl",
        "cluster",
        "namespace",
        "deployment",
        "rollout",
        "pod",
        "pods",
        "workload",
        "helm",
        "crashloop",
        "crashloopbackoff",
        "кубер",
        "кубернет",
        "кластер",
        "неймспейс",
        "деплоймент",
        "поды",
        "роллаут",
    ),
    "pilot-gitlab-failed-pipeline-mr": (
        "gitlab",
        "ci",
        "ci/cd",
        "failed pipeline",
        "pipeline failed",
        "merge request",
        "mr",
        "job failed",
        "build failed",
        "пайплайн упал",
        "упал pipeline",
        "сборк",
        "джоб",
        "мердж",
    ),
    "pilot-database-diagnostics-maintenance": (
        "database",
        "db",
        "postgres",
        "postgresql",
        "mysql",
        "mariadb",
        "mongodb",
        "sql",
        "slow query",
        "slow queries",
        "locks",
        "replication",
        "schema",
        "база",
        "бд",
        "постгрес",
        "запрос",
        "лок",
        "репликац",
    ),
    "pilot-observability-incident-response": (
        "observability",
        "grafana",
        "prometheus",
        "loki",
        "pagerduty",
        "jira",
        "sentry",
        "oncall",
        "outage",
        "slo",
        "error rate",
        "latency",
        "графана",
        "прометей",
        "дежурн",
        "авари",
    ),
    "pilot-linux-package-maintenance": (
        "package",
        "packages",
        "pkg",
        "pkgs",
        "apt",
        "apt-get",
        "yum",
        "dnf",
        "security update",
        "security patch",
        "update packages",
        "upgrade packages",
        "patch packages",
        "package update",
        "обнови пакеты",
        "обновить пакеты",
        "обновление пакетов",
        "пакеты обнов",
        "патч",
    ),
    "pilot-linux-disk-cleanup": (
        "disk cleanup",
        "disk full",
        "disk usage",
        "free space",
        "cleanup disk",
        "clean disk",
        "journal vacuum",
        "journalctl vacuum",
        "tmp cleanup",
        "tmp files",
        "var tmp",
        "du",
        "df",
        "место на диске",
        "диск заполнен",
        "диск забит",
        "очисти диск",
        "очистка диска",
        "свободное место",
        "journal vacuum",
        "временные файлы",
    ),
    "pilot-backup-restore-check": (
        "backup",
        "backups",
        "restore check",
        "restore test",
        "backup check",
        "backup verification",
        "verify backup",
        "latest backup",
        "archive integrity",
        "dump",
        "snapshot backup",
        "бэкап",
        "бекап",
        "резервн",
        "backup свеж",
        "проверь backup",
        "проверить backup",
        "восстановлен",
    ),
    "pilot-service-config-validate-restart": (
        "linux",
        "service",
        "systemd",
        "nginx",
        "apache",
        "restart",
        "reload",
        "config",
        "configuration",
        "healthcheck",
        "health check",
        "journalctl",
        "сервис",
        "служб",
        "рестарт",
        "перезапуск",
        "перезапусти",
        "конфиг",
        "логи",
        "лог",
    ),
}
