import { expect, test, type Page } from "@playwright/test";
import { credentials, login, assertNoOverflow } from "./helpers";

test.use({ actionTimeout: 15_000, navigationTimeout: 20_000 });

type User = {
  id: number;
  username: string;
  email: string;
  is_active: boolean;
  groups: { id: number; name: string }[];
  explicit_permissions: Record<string, boolean>;
  effective_permissions: Record<string, boolean>;
  permission_sources: Record<string, string>;
};
type Group = { id: number; name: string; members: { id: number }[] };
async function headers(page: Page) {
  const response = await page.request.get("/api/auth/csrf/");
  const body = await response.json();
  return { "X-CSRFToken": body.csrfToken, Origin: "http://127.0.0.1:8091" };
}
async function userByName(
  page: Page,
  username: string,
): Promise<User | undefined> {
  const response = await page.request.get("/api/access/users/");
  expect(response.ok()).toBeTruthy();
  return ((await response.json()).users as User[]).find(
    (user) => user.username === username,
  );
}
async function cleanup(page: Page, username: string, groupName?: string) {
  // Only entities generated by this test are eligible for cleanup.
  expect(username.startsWith("qa_gov_")).toBeTruthy();
  const authHeaders = await headers(page);
  const user = await userByName(page, username);
  if (user)
    await page.request.delete(`/api/access/users/${user.id}/`, {
      headers: authHeaders,
    });
  if (groupName) {
    expect(groupName.startsWith("qa_gov_")).toBeTruthy();
    const response = await page.request.get("/api/access/groups/");
    const group = ((await response.json()).groups as Group[]).find(
      (item) => item.name === groupName,
    );
    if (group)
      await page.request.delete(`/api/access/groups/${group.id}/`, {
        headers: authHeaders,
      });
  }
}
async function openUser(page: Page, username: string) {
  await page.goto("/governance/users");
  await page.getByPlaceholder("Найти пользователя или группу").fill(username);
  await page
    .getByRole("row")
    .filter({ hasText: username })
    .getByRole("button", { name: "Настроить", exact: true })
    .click();
  await expect(page.getByRole("dialog")).toBeVisible();
}
test.beforeEach(async ({ baseURL }) => {
  expect(
    baseURL,
    "Governance writes must stay on the isolated QA service",
  ).toBe("http://127.0.0.1:8091");
});

test("user and group lifecycle respects personal overrides and restores inheritance", async ({
  page,
}) => {
  test.setTimeout(120_000);
  const suffix = `${Date.now()}`;
  const username = `qa_gov_user_${suffix}`;
  const groupName = `qa_gov_group_${suffix}`;
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await login(page);
  try {
    await page.goto("/governance/groups");
    await page
      .getByRole("button", { name: "Создать группу", exact: true })
      .first()
      .click();
    let dialog = page.getByRole("dialog");
    await dialog.getByLabel("Название группы", { exact: true }).fill(groupName);
    await dialog
      .getByRole("tab", { name: "Права доступа", exact: true })
      .click();
    await dialog
      .getByLabel("Доступ: Серверы", { exact: true })
      .selectOption("allow");
    await dialog
      .getByRole("button", { name: "Сохранить группу", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);

    await page.goto("/governance/users");
    await page
      .getByRole("button", { name: "Добавить пользователя", exact: true })
      .click();
    dialog = page.getByRole("dialog");
    await dialog.getByLabel("Имя пользователя", { exact: true }).fill(username);
    await dialog
      .getByLabel("Рабочая почта", { exact: true })
      .fill(`${username}@example.test`);
    await dialog
      .getByLabel("Начальный пароль", { exact: true })
      .fill(credentials.password);
    await dialog
      .getByLabel("Профиль доступа", { exact: true })
      .selectOption("custom");
    await dialog
      .getByRole("checkbox", { name: groupName, exact: true })
      .check();
    await dialog
      .getByRole("button", { name: "Сохранить", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    let savedUser = await userByName(page, username);
    expect(savedUser?.groups.map((group) => group.name)).toContain(groupName);
    expect(savedUser?.effective_permissions.servers).toBe(true);
    expect(savedUser?.permission_sources.servers).toBe("group_explicit");
    expect(savedUser?.explicit_permissions.servers).toBeUndefined();

    await openUser(page, username);
    dialog = page.getByRole("dialog");
    await dialog
      .getByRole("tab", { name: "Права доступа", exact: true })
      .click();
    await dialog
      .getByLabel("Доступ: Серверы", { exact: true })
      .selectOption("deny");
    await dialog
      .getByRole("button", { name: "Сохранить", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    savedUser = await userByName(page, username);
    expect(savedUser?.effective_permissions.servers).toBe(false);
    expect(savedUser?.permission_sources.servers).toBe("user_explicit");

    await page.goto("/governance/permissions");
    await page
      .getByRole("textbox", { name: "Поиск…", exact: true })
      .fill(username);
    await page
      .getByLabel(`Доступ к servers для ${username}`, { exact: true })
      .selectOption("allow");
    await expect
      .poll(
        async () =>
          (await userByName(page, username))?.effective_permissions.servers,
      )
      .toBe(true);
    const row = page
      .getByRole("row")
      .filter({ hasText: username })
      .filter({ hasText: "Серверы" });
    await row
      .getByRole("button", { name: "Восстановить наследование", exact: true })
      .click();
    await page
      .getByRole("dialog")
      .getByRole("button", { name: "Удалить правило", exact: true })
      .click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    savedUser = await userByName(page, username);
    expect(savedUser?.explicit_permissions.servers).toBeUndefined();
    expect(savedUser?.effective_permissions.servers).toBe(true);
    expect(savedUser?.permission_sources.servers).toBe("group_explicit");
    await assertNoOverflow(page);

    await page.goto("/governance/users");
    await page.getByPlaceholder("Найти пользователя или группу").fill(username);
    await page
      .getByRole("button", { name: `Удалить ${username}`, exact: true })
      .click();
    dialog = page.getByRole("dialog");
    await expect(
      dialog.getByRole("button", { name: "Удалить пользователя", exact: true }),
    ).toBeDisabled();
    await dialog
      .getByLabel(`Введите «${username}»`, { exact: true })
      .fill(username);
    await dialog
      .getByRole("button", { name: "Удалить пользователя", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    expect(await userByName(page, username)).toBeUndefined();

    await page.goto("/governance/groups");
    await page
      .getByRole("textbox", { name: "Поиск…", exact: true })
      .fill(groupName);
    await page
      .getByRole("button", { name: `Удалить группу ${groupName}`, exact: true })
      .click();
    dialog = page.getByRole("dialog");
    await dialog
      .getByLabel(`Введите «${groupName}»`, { exact: true })
      .fill(groupName);
    await dialog
      .getByRole("button", { name: "Удалить группу", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    const groups = await page.request.get("/api/access/groups/");
    expect(
      ((await groups.json()).groups as Group[]).some(
        (group) => group.name === groupName,
      ),
    ).toBe(false);
    expect(errors).toEqual([]);
  } finally {
    await cleanup(page, username, groupName);
  }
});

test("failed user save preserves draft; password reset and account state persist", async ({
  page,
  browser,
}) => {
  test.setTimeout(120_000);
  const username = `qa_gov_account_${Date.now()}`;
  const nextPassword = `${credentials.password}_Revised`;
  await login(page);
  const create = await page.request.post("/api/access/users/", {
    headers: await headers(page),
    data: {
      username,
      password: credentials.password,
      access_profile: "custom",
      is_active: true,
      explicit_permissions: { servers: true },
    },
  });
  expect(create.ok()).toBeTruthy();
  try {
    await openUser(page, username);
    let dialog = page.getByRole("dialog");
    await dialog
      .getByLabel("Имя пользователя", { exact: true })
      .fill(credentials.admin.username);
    await dialog
      .getByLabel("Рабочая почта", { exact: true })
      .fill("edited-governance@example.test");
    const rejected = page.waitForResponse(
      (response) =>
        response.request().method() === "PUT" &&
        response.url().includes("/api/access/users/"),
    );
    await dialog
      .getByRole("button", { name: "Сохранить", exact: true })
      .click();
    expect((await rejected).status()).toBe(400);
    await expect(dialog).toBeVisible();
    await expect(
      dialog.getByLabel("Рабочая почта", { exact: true }),
    ).toHaveValue("edited-governance@example.test");
    await expect(dialog.getByRole("alert")).toContainText(
      "Username already exists",
    );
    await dialog.getByLabel("Имя пользователя", { exact: true }).fill(username);
    await dialog
      .getByRole("checkbox", { name: "Учётная запись активна", exact: true })
      .uncheck();
    await dialog
      .getByRole("button", { name: "Сохранить", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    expect((await userByName(page, username))?.is_active).toBe(false);
    expect((await userByName(page, username))?.email).toBe(
      "edited-governance@example.test",
    );

    await openUser(page, username);
    dialog = page.getByRole("dialog");
    await dialog
      .getByRole("checkbox", { name: "Учётная запись активна", exact: true })
      .check();
    await dialog
      .getByRole("button", { name: "Сохранить", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    await openUser(page, username);
    dialog = page.getByRole("dialog");
    await dialog.getByRole("tab", { name: "Пароль", exact: true }).click();
    await expect(
      dialog.getByLabel("Новый пароль", { exact: true }),
    ).toHaveValue("");
    await dialog.getByLabel("Новый пароль", { exact: true }).fill(nextPassword);
    await dialog
      .getByRole("button", { name: "Обновить пароль", exact: true })
      .click();
    await expect(dialog.getByRole("status")).toContainText(
      "Изменения сохранены",
    );
    await expect(
      dialog.getByLabel("Новый пароль", { exact: true }),
    ).toHaveValue("");

    const context = await browser.newContext({
      baseURL: "http://127.0.0.1:8091",
    });
    try {
      const csrf = await context.request.get("/api/auth/csrf/");
      const csrfToken = (await csrf.json()).csrfToken;
      const auth = await context.request.post("/api/auth/login/", {
        headers: { "X-CSRFToken": csrfToken, Origin: "http://127.0.0.1:8091" },
        data: { username, password: nextPassword, auth_mode: "local" },
      });
      expect(auth.ok()).toBeTruthy();
      const me = await context.request.get("/api/auth/session/");
      expect(me.ok()).toBeTruthy();
      const meBody = await me.json();
      expect(meBody.authenticated).toBe(true);
      expect(meBody.user.username).toBe(username);
    } finally {
      await context.close();
    }
  } finally {
    await cleanup(page, username);
  }
});

test("viewer cannot bypass governance restrictions through direct routes or writes", async ({
  page,
}) => {
  await login(page, "viewer");
  for (const path of [
    "/governance/groups",
    "/governance/permissions",
    "/settings/general",
    "/settings/identity",
  ]) {
    await page.goto(path);
    await expect(
      page.getByText("Недостаточно прав", { exact: true }),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: /Сохранить группу|Назначить право/ }),
    ).toHaveCount(0);
  }
  const response = await page.request.post("/api/access/groups/", {
    headers: await headers(page),
    data: { name: `qa_gov_forbidden_${Date.now()}` },
  });
  expect(response.status()).toBe(403);
  expect((await page.request.get("/api/access/users/")).status()).toBe(403);
  for (const path of [
    "/api/admin/dashboard/",
    "/api/admin/users/activity/",
    "/api/admin/users/sessions/",
    "/api/dashboard-custom/layout/admin/",
  ]) {
    expect((await page.request.get(path)).status()).toBe(403);
  }
  expect(
    (await page.request.get("/api/dashboard-custom/layout/user/")).status(),
  ).toBe(200);
});
