import { FIXED_DATE } from "./platformFixtureTypes";

export function makeAgentFixtureData() {
  const executionReadinessMissing = {
    required: true,
    ready: false,
    status: "missing",
    severity: "warning",
    title: "Execution worker не запущен",
    description: "Full/multi-агенты будут поставлены в очередь, но не начнут выполняться до запуска worker.",
    next_action: "Запустите worker: python manage.py run_agent_execution_plane --worker-key <unique-worker-key>",
    worker: {
      worker_kind: "agent_execution",
      worker_key: "default",
      status: "missing",
      is_stale: true,
      hostname: "",
      pid: null,
      command: "",
      heartbeat_at: null,
      lease_expires_at: null,
      last_started_at: null,
      last_stopped_at: null,
      last_cycle_started_at: null,
      last_cycle_finished_at: null,
      last_summary: {},
      last_error: "",
    },
  };

  const miniExecutionReadiness = {
    required: false,
    ready: true,
    status: "not_required",
    severity: "info",
    title: "Execution worker не требуется",
    description: "Mini-агенты выполняются inline и не требуют execution-plane worker.",
    next_action: "",
    worker: null,
  };

  const agentWorkerStates = {
    scheduled_agents: {
      worker_kind: "scheduled_agents",
      worker_key: "default",
      status: "running",
      is_stale: false,
      hostname: "sched-worker-01",
      pid: 7331,
      command: "python manage.py run_scheduled_agents --daemon --worker-key default",
      heartbeat_at: FIXED_DATE,
      lease_expires_at: "2026-03-01T08:03:00.000Z",
      last_started_at: FIXED_DATE,
      last_stopped_at: null,
      last_cycle_started_at: FIXED_DATE,
      last_cycle_finished_at: FIXED_DATE,
      last_summary: { scanned: 2, due: 1, launched_agents: 0, skipped: 2 },
      last_error: "",
    },
  };

  const agentRuntimeOverview = {
    status: "needs_attention",
    severity: "warning",
    summary: {
      configured_agents: 2,
      active_runs: 1,
      pending_runs: 1,
      running_runs: 0,
      waiting_runs: 0,
      queued_dispatches: 1,
      claimed_dispatches: 0,
      scheduled_agents: 1,
      scheduled_due_now: 1,
      issues: 1,
    },
    queue: {
      runs: { pending: 1, running: 0, waiting: 0 },
      dispatches: { queued: 1, claimed: 0 },
    },
    schedule: {
      total_scheduled: 1,
      enabled: 1,
      paused: 0,
      due_now: 1,
      worker_ready: true,
    },
    workers: agentWorkerStates,
    execution_readiness: executionReadinessMissing,
    issues: [
      {
        id: "execution_worker_not_ready",
        severity: "warning",
        title: "Execution worker не активен",
        description: "Full/multi-запуски есть в очереди, но worker не подтверждён.",
        next_action: "python manage.py run_agent_execution_plane --worker-key <unique-worker-key>",
      },
    ],
    commands: {
      execution_worker: "python manage.py run_agent_execution_plane --worker-key <unique-worker-key>",
      scheduled_agents_worker: "python manage.py run_scheduled_agents --daemon --worker-key default",
      ops_supervisor: "docker compose up -d --scale agent-execution=<replicas> agent-execution",
    },
    items: {
      active_runs: [
        {
          run_id: 901,
          agent_id: 202,
          agent_name: "Patch Rollout",
          agent_mode: "multi",
          server_id: 1,
          server_name: "Web-01",
          status: "pending",
          started_at: FIXED_DATE,
          completed_at: null,
          age_seconds: 125,
          duration_ms: 0,
          pending_question: "",
          is_stale_candidate: false,
          dispatch: null,
        },
      ],
      queued_dispatches: [
        {
          dispatch_id: 41,
          run_id: 901,
          agent_id: 202,
          agent_name: "Patch Rollout",
          agent_mode: "multi",
          server_id: 1,
          server_name: "Web-01",
          dispatch_kind: "launch",
          status: "queued",
          server_ids: [1],
          queued_at: FIXED_DATE,
          claimed_at: null,
          heartbeat_at: null,
          lease_expires_at: null,
          queued_age_seconds: 125,
          lease_seconds_left: null,
          claimed_by: "",
          attempt_count: 0,
          error: "",
        },
      ],
      scheduled_due: [
        {
          agent_id: 202,
          agent_name: "Patch Rollout",
          agent_mode: "multi",
          server_count: 1,
          server_names: ["Web-01"],
          schedule_minutes: 60,
          schedule_config: { mode: "interval", interval_minutes: 60 },
          last_run_at: "2026-03-01T07:00:00.000Z",
          next_due_at: FIXED_DATE,
          due_age_seconds: 0,
          active_run_id: 901,
          active_run_status: "pending",
        },
      ],
      stale_candidates: [],
    },
    generated_at: FIXED_DATE,
  };

  const serverAgents = [
    {
      id: 201,
      name: "Disk Audit",
      mode: "mini",
      mode_display: "Mini Agent",
      agent_type: "disk_report",
      agent_type_display: "Disk Report",
      server_count: 1,
      server_ids: [1],
      server_names: ["Web-01"],
      schedule_minutes: 0,
      schedule_config: { mode: "manual" },
      is_enabled: true,
      commands: ["df -h", "du -sh /var/log"],
      ai_prompt: "Summarize disk pressure.",
      goal: "",
      system_prompt: "",
      max_iterations: 20,
      allow_multi_server: false,
      tools_config: {},
      sudo_policy: "disabled",
      stop_conditions: [],
      skill_slugs: [],
      input_artifacts: [],
      report_delivery: { telegram: { enabled: false, chat_id: "", format: "brief", include_link: true } },
      session_timeout_seconds: 600,
      max_connections: 5,
      last_run_at: FIXED_DATE,
      last_run_status: "completed",
      last_run_id: 901,
      active_run_id: null,
      execution_readiness: miniExecutionReadiness,
      schedule_state: "manual",
      due_now: false,
      next_due_at: null,
      next_due_in_seconds: null,
    },
    {
      id: 202,
      name: "Patch Rollout",
      mode: "multi",
      mode_display: "Multi-Agent Pipeline",
      agent_type: "custom",
      agent_type_display: "Custom",
      server_count: 1,
      server_ids: [1],
      server_names: ["Web-01"],
      schedule_minutes: 15,
      schedule_config: { mode: "interval", interval_minutes: 15 },
      is_enabled: true,
      commands: [],
      ai_prompt: "",
      goal: "Validate patch readiness and collect evidence before rollout.",
      system_prompt: "",
      max_iterations: 20,
      allow_multi_server: true,
      tools_config: {},
      sudo_policy: "ask",
      stop_conditions: ["report ready"],
      skill_slugs: [],
      input_artifacts: [],
      report_delivery: { telegram: { enabled: true, chat_id: "", format: "brief", include_link: true } },
      session_timeout_seconds: 900,
      max_connections: 5,
      last_run_at: FIXED_DATE,
      last_run_status: "running",
      last_run_id: 901,
      active_run_id: 901,
      execution_readiness: executionReadinessMissing,
      schedule_state: "due",
      due_now: true,
      next_due_at: FIXED_DATE,
      next_due_in_seconds: 0,
    },
  ];
  return { executionReadinessMissing, miniExecutionReadiness, agentWorkerStates, agentRuntimeOverview, serverAgents };
}
