import { FIXED_DATE } from "./platformFixtureTypes";

export function makeAgentRunFixtureData() {
  const agentRunPlanTasks = [
    {
      id: 1,
      name: "Inspect service health",
      description: "Collect systemd and disk status before applying changes.",
      status: "done",
      thought: "Baseline captured.",
      iterations: [],
      result: "nginx is active, disk usage is below threshold.",
      error: "",
      orchestrator_decision: null,
      started_at: FIXED_DATE,
      completed_at: FIXED_DATE,
    },
    {
      id: 2,
      name: "Apply patch window checks",
      description: "Verify the maintenance window and prepare the package update.",
      status: "running",
      thought: "Checking package locks and pending services.",
      iterations: [
        {
          iteration: 1,
          thought: "Check package lock state.",
          action: "run_command",
          args: { command: "apt list --upgradable" },
          observation: "3 packages can be upgraded.",
          timestamp: FIXED_DATE,
        },
      ],
      result: "",
      error: "",
      orchestrator_decision: null,
      started_at: FIXED_DATE,
      completed_at: null,
    },
    {
      id: 3,
      name: "Write completion report",
      description: "Summarize commands, risks, and next verification steps.",
      status: "pending",
      thought: "",
      iterations: [],
      result: "",
      error: "",
      orchestrator_decision: null,
      started_at: null,
      completed_at: null,
    },
  ];

  const agentRunEvents = [
    {
      id: 1,
      run_id: 901,
      event_type: "agent_background_started",
      task_id: null,
      message: "Agent run started.",
      payload: { server: "Web-01" },
      created_at: FIXED_DATE,
      severity: "info",
      source: "agent",
      title: "Фоновый запуск начат",
      summary: "Worker начал выполнение агента.",
      phase: "starting",
      category: "system",
      important: true,
    },
    {
      id: 2,
      run_id: 901,
      event_type: "agent_task_start",
      task_id: 2,
      message: "Running package readiness checks.",
      payload: { command: "apt list --upgradable" },
      created_at: FIXED_DATE,
      severity: "info",
      source: "task",
      title: "Apply patch window checks",
      summary: "Running package readiness checks.",
      phase: "executing",
      category: "task",
      important: true,
    },
    {
      id: 3,
      run_id: 901,
      event_type: "agent_task_failed",
      task_id: 2,
      message: "Package lock check returned a warning exit code.",
      payload: { command: "apt-get check", exit_code: 100 },
      created_at: FIXED_DATE,
      severity: "critical",
      source: "command",
      title: "Package lock check failed",
      summary: "apt-get check вернул код 100, rollout требует ручной проверки.",
      phase: "executing",
      category: "task",
      important: true,
    },
  ];

  const agentRunLogs = [
    {
      id: "cmd-1",
      index: 1,
      kind: "command",
      title: "systemctl is-active nginx",
      command: "systemctl is-active nginx",
      stdout: "active\n",
      stderr: "",
      exit_code: 0,
      duration_ms: 320,
      status: "completed",
      severity: "success",
      timestamp: FIXED_DATE,
    },
    {
      id: "cmd-2",
      index: 2,
      kind: "command",
      title: "apt-get check",
      command: "apt-get check",
      stdout: "",
      stderr: "E: dpkg was interrupted, you must manually run 'dpkg --configure -a'\n",
      exit_code: 100,
      duration_ms: 840,
      status: "failed",
      severity: "critical",
      timestamp: FIXED_DATE,
    },
  ];

  const agentRunSteps = agentRunPlanTasks.map((task, index) => ({
    id: String(task.id),
    index: index + 1,
    title: task.name,
    description: task.description,
    command: task.iterations[0]?.action || "",
    status: task.status,
    severity: task.status === "done" ? "success" : task.status === "failed" ? "critical" : "info",
    status_label: task.status === "done" ? "Завершено" : task.status === "running" ? "Выполняется" : "Ожидает",
    duration_ms: task.status === "done" ? 1250 : 0,
    details: task.result || task.thought,
    error: task.error,
    started_at: task.started_at,
    completed_at: task.completed_at,
  }));

  const agentRunReport = {
    success: true,
    schema_version: 1,
    run: {
      id: 901,
      agent_id: 202,
      agent_name: "Patch Rollout",
      agent_type: "custom",
      agent_mode: "multi",
      server_name: "Web-01",
      server_id: 1,
      status: "running",
      duration_ms: 125000,
      started_at: FIXED_DATE,
      completed_at: null,
      total_iterations: 4,
      connected_servers: [{ server_id: 1, server_name: "Web-01" }],
      pending_question: "",
      dispatch: {
        id: 701,
        run_id: 901,
        dispatch_kind: "launch",
        status: "queued",
        server_ids: [1],
        plan_only: false,
        queued_at: FIXED_DATE,
        claimed_at: null,
        heartbeat_at: null,
        lease_expires_at: null,
        completed_at: null,
        claimed_by: "",
        attempt_count: 0,
        error: "",
        metadata: {},
      },
    },
    report_state: {
      phase: "executing",
      report_ready: false,
      artifacts_ready: false,
      is_terminal: false,
      headline: "Агент выполняет проверки",
      description:
        "Идёт сбор данных, выполнение команд и накопление доказательств для финального отчёта. Уже есть проблемные сигналы: 2. Dispatch ждёт в очереди 2m 5s. Статус worker: missing.",
      current_step: "Execution worker не принимает запуск",
      next_expected: "Запустите worker: python manage.py run_agent_execution_plane --worker-key <unique-worker-key>",
      progress: 62,
      execution_state: {
        status: "worker_missing",
        severity: "warning",
        title: "Execution worker не принимает запуск",
        description: "Dispatch ждёт в очереди 2m 5s. Статус worker: missing.",
        next_action: "Запустите worker: python manage.py run_agent_execution_plane --worker-key <unique-worker-key>",
        dispatch: {
          id: 701,
          run_id: 901,
          dispatch_kind: "launch",
          status: "queued",
          server_ids: [1],
          plan_only: false,
          queued_at: FIXED_DATE,
          claimed_at: null,
          heartbeat_at: null,
          lease_expires_at: null,
          completed_at: null,
          claimed_by: "",
          attempt_count: 0,
          error: "",
          metadata: {},
        },
        worker: {
          worker_kind: "agent_execution",
          worker_key: "",
          status: "missing",
          is_stale: true,
          hostname: "",
          pid: null,
          command: "",
          heartbeat_at: null,
          heartbeat_age_ms: null,
          lease_expires_at: null,
          last_started_at: null,
          last_stopped_at: null,
          last_cycle_started_at: null,
          last_cycle_finished_at: null,
          last_summary: {},
          last_error: "",
        },
        queued_age_ms: 125000,
        queued_for: "2m 5s",
        heartbeat_age_ms: null,
        heartbeat_age: "—",
        lease_expired: false,
        worker_ready: false,
      },
    },
    artifact_state: {
      ready: false,
      title: "Артефакты ещё не готовы",
      description: "Артефакты появятся только после того, как агент сохранит финальный markdown-отчёт.",
      empty_title: "Артефакты появятся после финального отчёта",
      empty_description: "После выполнения агент соберёт итоговый markdown-отчёт.",
    },
    report: {
      schema_version: 1,
      title: "Patch Rollout",
      subtitle:
        "Идёт сбор данных, выполнение команд и накопление доказательств для финального отчёта. Уже есть проблемные сигналы: 2. Dispatch ждёт в очереди 2m 5s. Статус worker: missing.",
      status: "running",
      status_label: "Выполняется",
      severity: "high",
      summary:
        "Идёт сбор данных, выполнение команд и накопление доказательств для финального отчёта. Уже есть проблемные сигналы: 2. Dispatch ждёт в очереди 2m 5s. Статус worker: missing.",
      root_cause: null,
      markdown: "",
      meta: {
        server: "Web-01",
        window: FIXED_DATE,
        analysis_duration: "2m 5s",
        finished_at: null,
        started_at: FIXED_DATE,
      },
      kpis: [
        { id: "status", label: "Статус", value: "Выполняется", hint: "running", severity: "info" },
        { id: "duration", label: "Длительность", value: "2m 5s", hint: "runtime", severity: "info" },
        { id: "scope", label: "Серверы", value: "1", hint: "Web-01", severity: "info" },
        { id: "signals", label: "Сигналы", value: "3", hint: "1 проблемный", severity: "high" },
      ],
      findings: [
        {
          id: "md-finding-1",
          title: "Web service живой, базовое состояние в норме.",
          description: "",
          severity: "info",
          source: "report",
        },
        {
          id: "log-cmd-2",
          title: "Команда завершилась с кодом 100",
          description: "apt-get check",
          severity: "critical",
          source: "command",
        },
      ],
      risks: [
        {
          id: "risk-log-cmd-2",
          title: "Команда завершилась с кодом 100",
          description: "apt-get check",
          severity: "critical",
          source: "command",
        },
      ],
      recommendations: [
        {
          id: "md-action-1",
          priority: "P1",
          title: "Проверить dpkg --configure -a на Web-01.",
          description: "",
          owner: "Оператор",
          done: false,
        },
        {
          id: "md-action-2",
          priority: "P2",
          title: "Повторить apt-get check перед продолжением rollout.",
          description: "",
          owner: "Оператор",
          done: false,
        },
      ],
    },
    events: agentRunEvents,
    logs: agentRunLogs,
    agent_steps: agentRunSteps,
    artifacts: [],
    generated_at: FIXED_DATE,
  };

  return { agentRunPlanTasks, agentRunEvents, agentRunLogs, agentRunSteps, agentRunReport };
}
