# Generated by Django 6.0.5 on 2026-06-25 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source_url', models.CharField(max_length=500)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PluginPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140)),
                ('version', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('publisher_id', models.CharField(max_length=120)),
                ('publisher_name', models.CharField(max_length=160)),
                ('source', models.CharField(choices=[('builtin', 'Built-in'), ('local', 'Local package'), ('catalog', 'Catalog')], default='builtin', max_length=20)),
                ('package_hash', models.CharField(blank=True, default='', max_length=128)),
                ('manifest', models.JSONField(default=dict)),
                ('risk_tier', models.CharField(default='info', max_length=40)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('signature_status', models.CharField(choices=[('unsigned', 'Unsigned'), ('builtin', 'Built-in'), ('signed', 'Signed'), ('invalid', 'Invalid')], default='unsigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plugin_id', '-created_at'],
                'indexes': [models.Index(fields=['plugin_id'], name='pm_pkg_plugin_idx'), models.Index(fields=['source', 'review_status'], name='pm_pkg_source_review_idx')],
                'constraints': [models.UniqueConstraint(fields=('plugin_id', 'version'), name='pm_pkg_plugin_version_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PluginInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('blocked', 'Blocked'), ('quarantined', 'Quarantined'), ('uninstalling', 'Uninstalling')], default='disabled', max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('health_status', models.CharField(blank=True, default='', max_length=30)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_installations', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='plugin_marketplace.pluginpackage')),
            ],
            options={
                'ordering': ['plugin_id'],
            },
        ),
        migrations.CreateModel(
            name='PluginPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=160)),
                ('reason', models.TextField(blank=True, default='')),
                ('risk_tier', models.CharField(default='read', max_length=40)),
                ('granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_permission_grants', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='plugin_marketplace.plugininstallation')),
            ],
            options={
                'ordering': ['installation_id', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='PluginSecretBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('secret_ref', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_secret_bindings', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_bindings', to='plugin_marketplace.plugininstallation')),
            ],
            options={
                'ordering': ['installation_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140)),
                ('version', models.CharField(max_length=80)),
                ('manifest', models.JSONField(default=dict)),
                ('package_url', models.CharField(blank=True, default='', max_length=500)),
                ('compatibility', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('signature_status', models.CharField(choices=[('unsigned', 'Unsigned'), ('builtin', 'Built-in'), ('signed', 'Signed'), ('invalid', 'Invalid')], default='unsigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plugin_marketplace.marketplacesource')),
            ],
            options={
                'ordering': ['plugin_id', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'plugin_id', 'version'), name='pm_catalog_source_plugin_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PluginInstallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140)),
                ('event_type', models.CharField(max_length=80)),
                ('status', models.CharField(default='info', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_events', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='plugin_marketplace.plugininstallation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['plugin_id', '-created_at'], name='pm_event_plugin_created_idx'), models.Index(fields=['event_type', '-created_at'], name='pm_event_type_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='plugininstallation',
            index=models.Index(fields=['status'], name='pm_install_status_idx'),
        ),
        migrations.AddIndex(
            model_name='plugininstallation',
            index=models.Index(fields=['plugin_id', 'status'], name='pm_install_plugin_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginpermissiongrant',
            index=models.Index(fields=['scope', 'granted'], name='pm_perm_scope_grant_idx'),
        ),
        migrations.AddConstraint(
            model_name='pluginpermissiongrant',
            constraint=models.UniqueConstraint(fields=('installation', 'scope'), name='pm_permission_install_scope_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pluginsecretbinding',
            constraint=models.UniqueConstraint(fields=('installation', 'key'), name='pm_secret_install_key_uniq'),
        ),
    ]
