# Generated by Django 6.0.5 on 2026-06-27 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='listing_status',
            field=models.CharField(choices=[('published', 'Published'), ('deprecated', 'Deprecated'), ('unpublished', 'Unpublished')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='moderation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='unpublished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PluginPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('support_url', models.CharField(blank=True, default='', max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_publishers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PluginRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='plugin_marketplace.marketplacecatalogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PluginSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140)),
                ('version', models.CharField(max_length=80)),
                ('manifest', models.JSONField(default=dict)),
                ('package_url', models.CharField(blank=True, default='', max_length=500)),
                ('compatibility', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=30)),
                ('scan_report', models.JSONField(blank=True, default=dict)),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='plugin_marketplace.marketplacecatalogitem')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='plugin_marketplace.pluginpackage')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='plugin_marketplace.pluginpublisher')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'plugin_id'],
            },
        ),
        migrations.CreateModel(
            name='PluginAbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140)),
                ('category', models.CharField(default='policy', max_length=80)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='plugin_marketplace.marketplacecatalogitem')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_abuse_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_abuse_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['plugin_id', 'status'], name='pm_abuse_plugin_status_idx'), models.Index(fields=['status', '-created_at'], name='pm_abuse_status_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pluginpublisher',
            index=models.Index(fields=['slug', 'verified'], name='pm_publisher_slug_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginrating',
            index=models.Index(fields=['catalog_item', 'rating'], name='pm_rating_item_rating_idx'),
        ),
        migrations.AddConstraint(
            model_name='pluginrating',
            constraint=models.UniqueConstraint(fields=('catalog_item', 'user'), name='pm_rating_item_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='pluginsubmission',
            index=models.Index(fields=['status', '-created_at'], name='pm_submission_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pluginsubmission',
            index=models.Index(fields=['plugin_id', 'version'], name='pm_submission_plugin_version_idx'),
        ),
    ]
