# Generated by Django 6.0.5 on 2026-06-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0002_marketplacecatalogitem_deprecated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstallation',
            name='health_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugininstallation',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
