# Generated by Django 6.0.5 on 2026-06-28 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0003_plugininstallation_health_failure_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='license_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pluginpackage',
            name='license_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pluginpackage',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pluginpackage',
            name='signature_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pluginsubmission',
            name='license_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pluginsubmission',
            name='pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PluginLicenseGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140)),
                ('license_key', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_license_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plugin_id', '-updated_at'],
                'indexes': [models.Index(fields=['plugin_id', 'status'], name='pm_license_plugin_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('plugin_id', 'user'), name='pm_license_plugin_user_uniq')],
            },
        ),
    ]
