# Generated by Django 6.0.5 on 2026-06-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0004_marketplacecatalogitem_license_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginpackage',
            name='attestations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
