# Generated by Django 6.0.5 on 2026-06-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0005_pluginpackage_attestations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginpackage',
            name='dependency_scan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pluginpackage',
            name='sbom',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
