# Generated by Django 6.0.5 on 2026-06-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0006_pluginpackage_dependency_scan_pluginpackage_sbom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginpublisher',
            name='identity_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pluginpublisher',
            name='identity_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='pluginpublisher',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
