# Generated by Django 6.0.5 on 2026-06-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0007_pluginpublisher_identity_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginCompatibilityJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140)),
                ('version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('isolation_mode', models.CharField(default='in_process_no_code', max_length=80)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_jobs', to='plugin_marketplace.marketplacecatalogitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['plugin_id', '-created_at'], name='pm_compat_plugin_created_idx'), models.Index(fields=['status', '-created_at'], name='pm_compat_status_created_idx')],
            },
        ),
    ]
