# Generated by Django 6.0.5 on 2026-06-28 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0008_plugincompatibilityjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='install_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='last_installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacecatalogitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PluginCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PluginCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='plugin_marketplace.marketplacecatalogitem')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plugin_marketplace.plugincollection')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PluginMarketplacePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=140, unique=True)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_marketplace_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plugin_id'],
            },
        ),
        migrations.AddIndex(
            model_name='plugincollection',
            index=models.Index(fields=['is_public', 'sort_order'], name='pm_collection_public_order_idx'),
        ),
        migrations.AddIndex(
            model_name='plugincollectionitem',
            index=models.Index(fields=['collection', 'position'], name='pm_collection_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='plugincollectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'catalog_item'), name='pm_collection_item_uniq'),
        ),
        migrations.AddIndex(
            model_name='pluginmarketplacepolicy',
            index=models.Index(fields=['decision', 'plugin_id'], name='pm_policy_decision_plugin_idx'),
        ),
    ]
