# Generated by Django 6.0.5 on 2026-06-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('plugin_marketplace', '0009_marketplacecatalogitem_install_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstallation',
            name='scoped_groups',
            field=models.ManyToManyField(blank=True, related_name='scoped_plugin_installations', to='auth.group'),
        ),
    ]
