# Generated by Django 6.0.5 on 2026-06-28 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_marketplace', '0010_plugininstallation_scoped_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginCommerceSettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('provider', models.CharField(default='manual', max_length=40)),
                ('provider_settlement_id', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('dry_run', 'Dry run'), ('exported', 'Exported'), ('submitted', 'Submitted'), ('reconciled', 'Reconciled'), ('failed', 'Failed')], default='dry_run', max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('plugins', models.JSONField(blank=True, default=list)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_commerce_settlement_batches', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_commerce_settlement_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['provider', 'status'], name='pm_settle_provider_status_idx'), models.Index(fields=['status', '-updated_at'], name='pm_settle_status_updated_idx'), models.Index(fields=['provider_settlement_id'], name='pm_settle_provider_id_idx')],
            },
        ),
    ]
