# Generated by Codex on 2026-06-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_marketplace", "0011_plugincommercesettlementbatch"),
    ]

    operations = [
        migrations.DeleteModel(name="PluginCommerceSettlementBatch"),
        migrations.DeleteModel(name="PluginLicenseGrant"),
        migrations.DeleteModel(name="PluginCollectionItem"),
        migrations.DeleteModel(name="PluginCollection"),
        migrations.DeleteModel(name="PluginMarketplacePolicy"),
        migrations.DeleteModel(name="PluginAbuseReport"),
        migrations.DeleteModel(name="PluginRating"),
        migrations.DeleteModel(name="PluginSubmission"),
        migrations.DeleteModel(name="PluginPublisher"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="deprecated_at"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="install_count"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="last_installed_at"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="last_viewed_at"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="license_required"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="listing_status"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="moderation_note"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="pricing"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="published_at"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="unpublished_at"),
        migrations.RemoveField(model_name="marketplacecatalogitem", name="view_count"),
        migrations.RemoveField(model_name="pluginpackage", name="license_policy"),
    ]
