"""Server monitoring, alerting, and worker-state models."""

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from servers.models_inventory import Server


class ServerHealthCheck(models.Model):
    """Periodic health check results for a server."""

    STATUS_HEALTHY = "healthy"
    STATUS_WARNING = "warning"
    STATUS_CRITICAL = "critical"
    STATUS_UNREACHABLE = "unreachable"
    STATUS_CHOICES = [
        (STATUS_HEALTHY, "Healthy"),
        (STATUS_WARNING, "Warning"),
        (STATUS_CRITICAL, "Critical"),
        (STATUS_UNREACHABLE, "Unreachable"),
    ]

    server = models.ForeignKey(Server, on_delete=models.CASCADE, related_name="health_checks")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_HEALTHY)

    cpu_percent = models.FloatField(null=True, blank=True)
    memory_percent = models.FloatField(null=True, blank=True)
    memory_used_mb = models.IntegerField(null=True, blank=True)
    memory_total_mb = models.IntegerField(null=True, blank=True)
    disk_percent = models.FloatField(null=True, blank=True)
    disk_used_gb = models.FloatField(null=True, blank=True)
    disk_total_gb = models.FloatField(null=True, blank=True)
    load_1m = models.FloatField(null=True, blank=True)
    load_5m = models.FloatField(null=True, blank=True)
    load_15m = models.FloatField(null=True, blank=True)
    uptime_seconds = models.BigIntegerField(null=True, blank=True)
    process_count = models.IntegerField(null=True, blank=True)

    response_time_ms = models.IntegerField(null=True, blank=True)
    is_deep = models.BooleanField(default=False)
    raw_output = models.JSONField(default=dict, blank=True)
    checked_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-checked_at"]
        indexes = [
            models.Index(fields=["server", "-checked_at"]),
            models.Index(fields=["status", "-checked_at"]),
            # core_ui.history_retention prunes this table by checked_at across all
            # servers; without a leading index that degrades into a sequential scan.
            models.Index(fields=["checked_at"], name="srv_health_checked_idx"),
        ]

    def __str__(self):
        return f"{self.server.name}: {self.status} @ {self.checked_at}"


class ServerAlert(models.Model):
    """Alerts generated by server health monitoring."""

    TYPE_CPU = "cpu"
    TYPE_MEMORY = "memory"
    TYPE_DISK = "disk"
    TYPE_SERVICE = "service"
    TYPE_LOG_ERROR = "log_error"
    TYPE_UNREACHABLE = "unreachable"
    TYPE_FORECAST = "forecast"
    TYPE_CHOICES = [
        (TYPE_CPU, "High CPU"),
        (TYPE_MEMORY, "High Memory"),
        (TYPE_DISK, "High Disk"),
        (TYPE_SERVICE, "Failed Service"),
        (TYPE_LOG_ERROR, "Log Error"),
        (TYPE_UNREACHABLE, "Unreachable"),
        (TYPE_FORECAST, "Forecast"),
    ]

    SEVERITY_INFO = "info"
    SEVERITY_WARNING = "warning"
    SEVERITY_CRITICAL = "critical"
    SEVERITY_CHOICES = [
        (SEVERITY_INFO, "Info"),
        (SEVERITY_WARNING, "Warning"),
        (SEVERITY_CRITICAL, "Critical"),
    ]

    server = models.ForeignKey(Server, on_delete=models.CASCADE, related_name="alerts")
    alert_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES, default=SEVERITY_WARNING)
    title = models.CharField(max_length=255)
    message = models.TextField(blank=True)
    is_resolved = models.BooleanField(default=False)
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="resolved_alerts"
    )
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["server", "-created_at"]),
            models.Index(fields=["is_resolved", "-created_at"]),
            models.Index(fields=["severity", "-created_at"]),
        ]

    def __str__(self):
        return f"[{self.severity}] {self.server.name}: {self.title}"


class ServerWatcherDraft(models.Model):
    """Persisted watcher suggestion for operator review."""

    STATUS_OPEN = "open"
    STATUS_ACKNOWLEDGED = "acknowledged"
    STATUS_RESOLVED = "resolved"
    STATUS_SUPPRESSED = "suppressed"
    STATUS_CHOICES = [
        (STATUS_OPEN, "Open"),
        (STATUS_ACKNOWLEDGED, "Acknowledged"),
        (STATUS_RESOLVED, "Resolved"),
        (STATUS_SUPPRESSED, "Suppressed"),
    ]

    server = models.ForeignKey(Server, on_delete=models.CASCADE, related_name="watcher_drafts")
    fingerprint = models.CharField(max_length=64)
    severity = models.CharField(
        max_length=20, choices=ServerAlert.SEVERITY_CHOICES, default=ServerAlert.SEVERITY_WARNING
    )
    recommended_role = models.CharField(max_length=50, default="infra_scout")
    objective = models.TextField()
    reasons = models.JSONField(default=list, blank=True)
    memory_excerpt = models.JSONField(default=list, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_OPEN)
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(default=timezone.now)
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    acknowledged_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="acknowledged_server_watcher_drafts",
    )
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-last_seen_at"]
        unique_together = ["server", "fingerprint"]
        indexes = [
            models.Index(fields=["server", "status", "-last_seen_at"]),
            models.Index(fields=["status", "-last_seen_at"]),
        ]

    def __str__(self):
        return f"{self.server.name}: {self.objective[:80]}"


class BackgroundWorkerState(models.Model):
    """Lease and heartbeat state for long-running background workers."""

    KIND_MEMORY_DREAMS = "memory_dreams"
    KIND_AGENT_EXECUTION = "agent_execution"
    KIND_SCHEDULED_AGENTS = "scheduled_agents"
    KIND_WATCHERS = "watchers"
    KIND_AI_PROVIDER_AUTH = "ai_provider_auth"
    KIND_CHOICES = [
        (KIND_MEMORY_DREAMS, "Memory Dreams"),
        (KIND_AGENT_EXECUTION, "Agent Execution"),
        (KIND_SCHEDULED_AGENTS, "Scheduled Agents"),
        (KIND_WATCHERS, "Watchers"),
        (KIND_AI_PROVIDER_AUTH, "AI Provider Authentication"),
    ]

    STATUS_IDLE = "idle"
    STATUS_RUNNING = "running"
    STATUS_ERROR = "error"
    STATUS_STOPPED = "stopped"
    STATUS_CHOICES = [
        (STATUS_IDLE, "Idle"),
        (STATUS_RUNNING, "Running"),
        (STATUS_ERROR, "Error"),
        (STATUS_STOPPED, "Stopped"),
    ]

    worker_kind = models.CharField(max_length=40, choices=KIND_CHOICES)
    worker_key = models.CharField(max_length=80, default="default")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_IDLE)
    hostname = models.CharField(max_length=255, blank=True)
    pid = models.IntegerField(null=True, blank=True)
    command = models.CharField(max_length=255, blank=True)
    heartbeat_at = models.DateTimeField(null=True, blank=True)
    lease_expires_at = models.DateTimeField(null=True, blank=True)
    last_started_at = models.DateTimeField(null=True, blank=True)
    last_stopped_at = models.DateTimeField(null=True, blank=True)
    last_cycle_started_at = models.DateTimeField(null=True, blank=True)
    last_cycle_finished_at = models.DateTimeField(null=True, blank=True)
    last_summary = models.JSONField(default=dict, blank=True)
    last_error = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["worker_kind", "worker_key"]
        unique_together = ["worker_kind", "worker_key"]
        indexes = [
            models.Index(fields=["worker_kind", "worker_key"]),
            models.Index(fields=["worker_kind", "status", "-heartbeat_at"]),
        ]

    def __str__(self):
        return f"{self.worker_kind}:{self.worker_key} ({self.status})"
