from django.urls import path

from .views import (
    command_history,
    server_agent_dashboard,
    server_agent_runs,
    server_agents,
    server_auth_session,
    server_context,
    server_crud,
    server_files,
    server_groups,
    server_insights,
    server_knowledge,
    server_linux_ui,
    server_linux_ui_workloads,
    server_memory,
    server_monitoring,
    server_monitoring_actions,
    server_ops,
    server_pages,
    server_playbooks,
    server_shares,
    snapshot_views,
)

app_name = "servers"

urlpatterns = [
    path("", server_pages.server_list, name="server_list"),
    path("api/frontend/bootstrap/", server_pages.frontend_bootstrap, name="frontend_bootstrap"),
    path("hub/", server_pages.multi_terminal, name="multi_terminal"),
    path("<int:server_id>/terminal/", server_pages.server_terminal_page, name="server_terminal"),
    path("<int:server_id>/terminal/minimal/", server_pages.terminal_minimal, name="terminal_minimal"),
    path("api/create/", server_crud.server_create, name="server_create"),
    path("api/<int:server_id>/update/", server_crud.server_update, name="server_update"),
    path("api/<int:server_id>/test/", server_ops.server_test_connection, name="server_test"),
    path("api/<int:server_id>/detect-os/", server_ops.server_detect_os, name="server_detect_os"),
    path("api/detect-os/batch/", server_ops.server_detect_os_batch, name="server_detect_os_batch"),
    path("api/<int:server_id>/execute/", server_ops.server_execute_command, name="server_execute"),
    path(
        "api/<int:server_id>/ui/capabilities/",
        server_linux_ui.server_linux_ui_capabilities,
        name="server_linux_ui_capabilities",
    ),
    path("api/<int:server_id>/ui/settings/", server_linux_ui.server_linux_ui_settings, name="server_linux_ui_settings"),
    path("api/<int:server_id>/ui/overview/", server_linux_ui.server_linux_ui_overview, name="server_linux_ui_overview"),
    path(
        "api/<int:server_id>/ui/services/",
        server_linux_ui_workloads.server_linux_ui_services,
        name="server_linux_ui_services",
    ),
    path(
        "api/<int:server_id>/ui/services/logs/",
        server_linux_ui_workloads.server_linux_ui_service_logs,
        name="server_linux_ui_service_logs",
    ),
    path(
        "api/<int:server_id>/ui/services/action/",
        server_linux_ui_workloads.server_linux_ui_service_action,
        name="server_linux_ui_service_action",
    ),
    path(
        "api/<int:server_id>/ui/processes/",
        server_linux_ui_workloads.server_linux_ui_processes,
        name="server_linux_ui_processes",
    ),
    path(
        "api/<int:server_id>/ui/processes/action/",
        server_linux_ui_workloads.server_linux_ui_process_action,
        name="server_linux_ui_process_action",
    ),
    path("api/<int:server_id>/ui/logs/", server_linux_ui.server_linux_ui_logs, name="server_linux_ui_logs"),
    path("api/<int:server_id>/ui/disk/", server_linux_ui.server_linux_ui_disk, name="server_linux_ui_disk"),
    path("api/<int:server_id>/ui/network/", server_linux_ui.server_linux_ui_network, name="server_linux_ui_network"),
    path("api/<int:server_id>/ui/packages/", server_linux_ui.server_linux_ui_packages, name="server_linux_ui_packages"),
    path(
        "api/<int:server_id>/ui/docker/",
        server_linux_ui_workloads.server_linux_ui_docker,
        name="server_linux_ui_docker",
    ),
    path(
        "api/<int:server_id>/ui/docker/logs/",
        server_linux_ui_workloads.server_linux_ui_docker_logs,
        name="server_linux_ui_docker_logs",
    ),
    path(
        "api/<int:server_id>/ui/docker/action/",
        server_linux_ui_workloads.server_linux_ui_docker_action,
        name="server_linux_ui_docker_action",
    ),
    path("api/<int:server_id>/files/", server_files.server_file_list, name="server_file_list"),
    path("api/<int:server_id>/files/read/", server_files.server_file_read_text, name="server_file_read_text"),
    path("api/<int:server_id>/files/write/", server_files.server_file_write_text, name="server_file_write_text"),
    path("api/<int:server_id>/files/chmod/", server_files.server_file_chmod, name="server_file_chmod"),
    path("api/<int:server_id>/files/chown/", server_files.server_file_chown, name="server_file_chown"),
    path("api/<int:server_id>/files/upload/", server_files.server_file_upload, name="server_file_upload"),
    path("api/<int:server_id>/files/download/", server_files.server_file_download, name="server_file_download"),
    path("api/<int:server_id>/files/rename/", server_files.server_file_rename, name="server_file_rename"),
    path("api/<int:server_id>/files/delete/", server_files.server_file_delete, name="server_file_delete"),
    path("api/<int:server_id>/files/mkdir/", server_files.server_file_mkdir, name="server_file_mkdir"),
    path("api/<int:server_id>/delete/", server_crud.server_delete, name="server_delete"),
    path("api/<int:server_id>/shares/", server_shares.server_share_list, name="server_share_list"),
    path("api/<int:server_id>/share/", server_shares.server_share_create, name="server_share_create"),
    path(
        "api/<int:server_id>/shares/<int:share_id>/revoke/",
        server_shares.server_share_revoke,
        name="server_share_revoke",
    ),
    path("api/groups/create/", server_groups.group_create, name="group_create"),
    path("api/groups/<int:group_id>/update/", server_groups.group_update, name="group_update"),
    path("api/groups/<int:group_id>/delete/", server_groups.group_delete, name="group_delete"),
    path("api/groups/<int:group_id>/add-member/", server_groups.group_add_member, name="group_add_member"),
    path("api/groups/<int:group_id>/remove-member/", server_groups.group_remove_member, name="group_remove_member"),
    path("api/groups/<int:group_id>/subscribe/", server_groups.group_subscribe, name="group_subscribe"),
    path("api/bulk-update/", server_groups.bulk_update_servers, name="bulk_update_servers"),
    path("api/global-context/", server_context.global_context_get, name="global_context_get"),
    path("api/global-context/save/", server_context.global_context_save, name="global_context_save"),
    path("api/groups/<int:group_id>/context/", server_context.group_context_get, name="group_context_get"),
    path("api/groups/<int:group_id>/context/save/", server_context.group_context_save, name="group_context_save"),
    path("api/<int:server_id>/get/", server_crud.server_get, name="server_get"),
    path("api/<int:server_id>/reveal-password/", server_crud.server_reveal_password, name="server_reveal_password"),
    path("api/<int:server_id>/knowledge/", server_knowledge.server_knowledge_list, name="server_knowledge_list"),
    path(
        "api/<int:server_id>/knowledge/create/",
        server_knowledge.server_knowledge_create,
        name="server_knowledge_create",
    ),
    path(
        "api/<int:server_id>/knowledge/<int:knowledge_id>/update/",
        server_knowledge.server_knowledge_update,
        name="server_knowledge_update",
    ),
    path(
        "api/<int:server_id>/knowledge/<int:knowledge_id>/delete/",
        server_knowledge.server_knowledge_delete,
        name="server_knowledge_delete",
    ),
    path(
        "api/<int:server_id>/memory/snapshots/",
        server_memory.server_memory_snapshots_user,
        name="server_memory_snapshots_user",
    ),
    path(
        "api/<int:server_id>/memory/snapshots/bulk-delete/",
        server_memory.server_memory_snapshots_bulk_delete_user,
        name="server_memory_snapshots_bulk_delete_user",
    ),
    path(
        "api/<int:server_id>/memory/snapshots/<int:snapshot_id>/update/",
        server_memory.server_memory_snapshot_update,
        name="server_memory_snapshot_update",
    ),
    path(
        "api/<int:server_id>/memory/snapshots/<int:snapshot_id>/delete/",
        server_memory.server_memory_snapshot_delete_user,
        name="server_memory_snapshot_delete_user",
    ),
    path("api/<int:server_id>/memory/purge/", server_memory.server_memory_purge_user, name="server_memory_purge_user"),
    path("api/<int:server_id>/memory/overview/", server_memory.server_memory_overview, name="server_memory_overview"),
    path(
        "api/<int:server_id>/memory/run-dreams/",
        server_memory.server_memory_run_dreams,
        name="server_memory_run_dreams",
    ),
    path(
        "api/<int:server_id>/memory/policy/",
        server_memory.server_memory_policy_update,
        name="server_memory_policy_update",
    ),
    path(
        "api/<int:server_id>/memory/snapshots/<int:snapshot_id>/archive/",
        server_memory.server_memory_snapshot_archive,
        name="server_memory_snapshot_archive",
    ),
    path(
        "api/<int:server_id>/memory/snapshots/<int:snapshot_id>/promote-note/",
        server_memory.server_memory_snapshot_promote_note,
        name="server_memory_snapshot_promote_note",
    ),
    path(
        "api/<int:server_id>/memory/snapshots/<int:snapshot_id>/promote-skill/",
        server_memory.server_memory_snapshot_promote_skill,
        name="server_memory_snapshot_promote_skill",
    ),
    path("api/master-password/set/", server_auth_session.set_master_password, name="set_master_password"),
    path("api/master-password/check/", server_auth_session.get_master_password, name="get_master_password"),
    path("api/master-password/clear/", server_auth_session.clear_master_password, name="clear_master_password"),
    # Monitoring
    path("api/admin/insights/", server_insights.admin_insights, name="admin_insights"),
    path("api/admin/insights/ai/run/", server_insights.admin_insights_ai_run, name="admin_insights_ai_run"),
    path("api/monitoring/dashboard/", server_monitoring.monitoring_dashboard, name="monitoring_dashboard"),
    path("api/monitoring/status/", server_monitoring.monitoring_status, name="monitoring_status"),
    path("api/monitoring/refresh/", server_monitoring.monitoring_refresh, name="monitoring_refresh"),
    path("api/<int:server_id>/health/", server_monitoring.server_health_history, name="server_health_history"),
    path("api/<int:server_id>/health/check/", server_monitoring.server_health_check_now, name="server_health_check_now"),
    path("api/alerts/", server_monitoring_actions.server_alerts_list, name="server_alerts_list"),
    path("api/watchers/scan/", server_monitoring_actions.server_watcher_scan, name="server_watcher_scan"),
    path("api/watchers/drafts/", server_monitoring_actions.server_watcher_drafts, name="server_watcher_drafts"),
    path(
        "api/watchers/drafts/<int:draft_id>/ack/",
        server_monitoring_actions.server_watcher_draft_ack,
        name="server_watcher_draft_ack",
    ),
    path(
        "api/watchers/drafts/<int:draft_id>/launch/",
        server_monitoring_actions.server_watcher_draft_launch,
        name="server_watcher_draft_launch",
    ),
    path(
        "api/alerts/<int:alert_id>/resolve/",
        server_monitoring_actions.server_alert_resolve,
        name="server_alert_resolve",
    ),
    path("api/monitoring/config/", server_monitoring_actions.monitoring_config, name="monitoring_config"),
    path("api/<int:server_id>/ai-analyze/", server_monitoring_actions.ai_analyze_server, name="ai_analyze_server"),
    # Agents (mini + full)
    path("api/agents/", server_agents.agent_list, name="agent_list"),
    path("api/agents/runtime/cleanup-stale/", server_agents.agent_runtime_cleanup_stale, name="agent_runtime_cleanup_stale"),
    path("api/agents/schedules/", server_agents.agent_schedule_overview, name="agent_schedule_overview"),
    path("api/agents/schedules/dispatch/", server_agents.agent_schedule_dispatch, name="agent_schedule_dispatch"),
    path("api/agents/templates/", server_agents.agent_templates, name="agent_templates"),
    path("api/agents/create/", server_agents.agent_create, name="agent_create"),
    path("api/agents/<int:agent_id>/update/", server_agents.agent_update, name="agent_update"),
    path("api/agents/<int:agent_id>/delete/", server_agents.agent_delete, name="agent_delete"),
    path("api/agents/<int:agent_id>/run/", server_agents.agent_run, name="agent_run"),
    path("api/agents/<int:agent_id>/stop/", server_agent_runs.agent_stop, name="agent_stop"),
    path("api/agents/<int:agent_id>/runs/", server_agent_runs.agent_runs, name="agent_runs"),
    path("api/agents/runs/<int:run_id>/", server_agent_runs.agent_run_detail, name="agent_run_detail"),
    path("api/agents/runs/<int:run_id>/report/", server_agent_runs.agent_run_report, name="agent_run_report"),
    path("api/agents/runs/<int:run_id>/report/deliver/", server_agent_runs.agent_run_report_deliver, name="agent_run_report_deliver"),
    path(
        "api/agents/runs/<int:run_id>/artifacts/download-all/",
        server_agent_runs.agent_run_artifacts_download_all,
        name="agent_run_artifacts_download_all",
    ),
    path(
        "api/agents/runs/<int:run_id>/artifacts/<int:artifact_id>/download/",
        server_agent_runs.agent_run_artifact_download,
        name="agent_run_artifact_download",
    ),
    path("api/agents/runs/<int:run_id>/log/", server_agent_runs.agent_run_log, name="agent_run_log"),
    path("api/agents/runs/<int:run_id>/events/", server_agent_runs.agent_run_events, name="agent_run_events"),
    path("api/agents/runs/<int:run_id>/reply/", server_agent_runs.agent_run_reply, name="agent_run_reply"),
    path("api/agents/dashboard/", server_agent_dashboard.agent_dashboard_runs, name="agent_dashboard_runs"),
    # Pipeline task editing
    path(
        "api/agents/runs/<int:run_id>/approve-plan/",
        server_agent_runs.agent_run_approve_plan,
        name="agent_run_approve_plan",
    ),
    path(
        "api/agents/runs/<int:run_id>/tasks/<int:task_id>/update/",
        server_agent_runs.agent_run_task_update,
        name="agent_run_task_update",
    ),
    path(
        "api/agents/runs/<int:run_id>/tasks/<int:task_id>/ai-refine/",
        server_agent_runs.agent_run_task_ai_refine,
        name="agent_run_task_ai_refine",
    ),
    # Terminal autocomplete
    path(
        "api/<int:server_id>/command-suggestions/",
        command_history.api_command_suggestions,
        name="api_command_suggestions",
    ),
    # Rollback snapshots (2.4)
    path("api/<int:server_id>/snapshots/", snapshot_views.snapshot_list, name="snapshot_list"),
    path("api/<int:server_id>/snapshots/<int:snapshot_id>/", snapshot_views.snapshot_detail, name="snapshot_detail"),
    path(
        "api/<int:server_id>/snapshots/<int:snapshot_id>/restore/",
        snapshot_views.snapshot_restore,
        name="snapshot_restore",
    ),
    # Automation / Playbooks
    path("api/playbooks/", server_playbooks.playbook_list, name="playbook_list"),
    path("api/playbooks/create/", server_playbooks.playbook_create, name="playbook_create"),
    path("api/playbooks/import/", server_playbooks.playbook_import, name="playbook_import"),
    path("api/playbooks/ansible/status/", server_playbooks.playbook_ansible_status, name="playbook_ansible_status"),
    path("api/playbooks/guided/", server_playbooks.playbook_guided_recipes, name="playbook_guided_recipes"),
    path("api/playbooks/guided/generate/", server_playbooks.playbook_guided_generate, name="playbook_guided_generate"),
    path("api/playbooks/templates/", server_playbooks.playbook_templates, name="playbook_templates"),
    path(
        "api/playbooks/templates/<slug:slug>/install/",
        server_playbooks.playbook_template_install,
        name="playbook_template_install",
    ),
    path("api/playbooks/inventory/preview/", server_playbooks.playbook_inventory_preview, name="playbook_inventory_preview"),
    path("api/playbooks/runs/", server_playbooks.playbook_run_list, name="playbook_run_list"),
    path("api/playbooks/runs/<int:run_id>/", server_playbooks.playbook_run_detail, name="playbook_run_detail"),
    path("api/playbooks/runs/<int:run_id>/cancel/", server_playbooks.playbook_run_cancel, name="playbook_run_cancel"),
    path(
        "api/playbooks/runs/<int:run_id>/rerun-failed/",
        server_playbooks.playbook_run_rerun_failed,
        name="playbook_run_rerun_failed",
    ),
    path("api/playbooks/<int:playbook_id>/", server_playbooks.playbook_detail, name="playbook_detail"),
    path("api/playbooks/<int:playbook_id>/update/", server_playbooks.playbook_update, name="playbook_update"),
    path("api/playbooks/<int:playbook_id>/delete/", server_playbooks.playbook_delete, name="playbook_delete"),
    path("api/playbooks/<int:playbook_id>/duplicate/", server_playbooks.playbook_duplicate, name="playbook_duplicate"),
    path("api/playbooks/<int:playbook_id>/run/", server_playbooks.playbook_run, name="playbook_run"),
]
