# Generated by Django 5.2.10 on 2026-03-30 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_pipelinerun_runtime_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_studio_agent_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcpserverpool',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Specific users who can view and use this MCP server', related_name='shared_studio_mcp_servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_studio_pipelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudioSkillAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Visible to all users with skill access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_studio_skills', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_studio_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Studio Skill Access',
                'verbose_name_plural': 'Studio Skill Access',
                'ordering': ['slug'],
            },
        ),
    ]
