# Generated by Django 6.0.2 on 2026-04-10 10:32

from django.db import migrations, models


def mark_existing_graphs_as_v1(apps, schema_editor):
    Pipeline = apps.get_model("studio", "Pipeline")
    PipelineTemplate = apps.get_model("studio", "PipelineTemplate")
    Pipeline.objects.all().update(graph_version=1)
    PipelineTemplate.objects.all().update(graph_version=1)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_agentconfig_shared_with_mcpserverpool_shared_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='graph_version',
            field=models.PositiveSmallIntegerField(default=2, help_text='Pipeline graph contract version.'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='entry_node_id',
            field=models.CharField(blank=True, default='', help_text='Selected trigger node id used as the run entry point.', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='routing_state',
            field=models.JSONField(blank=True, default=dict, help_text='Ephemeral in-process routing state for V2 pipeline runs: {activated_nodes, completed_nodes, pending_merges, queued_nodes, entry_node_id}'),
        ),
        migrations.AddField(
            model_name='pipelinetemplate',
            name='graph_version',
            field=models.PositiveSmallIntegerField(default=2, help_text='Template graph contract version.'),
        ),
        migrations.RunPython(mark_existing_graphs_as_v1, noop_reverse),
    ]
