# Generated by Django 5.2.10 on 2026-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_pipeline_graph_version_pipelinerun_entry_node_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinetrigger',
            name='monitoring_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Alert filter for monitoring triggers: {server_ids, severities, alert_types, container_names, match_text}'),
        ),
        migrations.AlterField(
            model_name='pipelinetrigger',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('webhook', 'Webhook'), ('schedule', 'Schedule (cron)'), ('monitoring', 'Monitoring alert')], default='manual', max_length=20),
        ),
    ]
