# Generated by Django 5.2.10 on 2026-04-16 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0023_add_memory_policy_override'),
        ('studio', '0007_pipelinetrigger_monitoring_filters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped'), ('hibernating', 'Hibernating')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agentconfig',
            index=models.Index(fields=['owner', '-updated_at'], name='studio_agen_owner_i_5de880_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserverpool',
            index=models.Index(fields=['owner', 'name'], name='studio_mcps_owner_i_a3aef9_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserverpool',
            index=models.Index(fields=['is_shared'], name='studio_mcps_is_shar_686c86_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['owner', '-updated_at'], name='studio_pipe_owner_i_5945d2_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['is_shared'], name='studio_pipe_is_shar_91f379_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['pipeline', 'status'], name='studio_pipe_pipelin_e74014_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['pipeline', '-created_at'], name='studio_pipe_pipelin_c7fdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['status', '-created_at'], name='studio_pipe_status_bc23cd_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinetrigger',
            index=models.Index(fields=['pipeline', 'trigger_type'], name='studio_pipe_pipelin_f20db4_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinetrigger',
            index=models.Index(fields=['is_active'], name='studio_pipe_is_acti_b557e3_idx'),
        ),
    ]
