# Generated by Codex on 2026-05-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0008_add_missing_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineDraftSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafting", "Drafting"),
                            ("needs_input", "Needs input"),
                            ("ready", "Ready"),
                            ("invalid", "Invalid"),
                            ("blocked", "Blocked"),
                            ("applied", "Applied"),
                            ("discarded", "Discarded"),
                        ],
                        default="drafting",
                        max_length=20,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("validate", "Validate"),
                            ("fix_run", "Fix run"),
                        ],
                        default="create",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("user_goal", models.TextField(blank=True, default="")),
                ("current_graph_snapshot", models.JSONField(blank=True, default=dict)),
                ("selected_node_id", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_draft_sessions",
                        to="studio.pipeline",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_draft_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_sessions",
                        to="studio.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PipelineDraftRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_message", models.TextField(blank=True, default="")),
                ("assistant_reply", models.TextField(blank=True, default="")),
                ("target_node_id", models.CharField(blank=True, default="", max_length=100)),
                ("node_patch", models.JSONField(blank=True, default=dict)),
                ("graph_patch", models.JSONField(blank=True, default=dict)),
                ("preview_nodes", models.JSONField(blank=True, default=list)),
                ("preview_edges", models.JSONField(blank=True, default=list)),
                ("validation", models.JSONField(blank=True, default=dict)),
                ("risk", models.JSONField(blank=True, default=dict)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("assumptions", models.JSONField(blank=True, default=list)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("resource_plan", models.JSONField(blank=True, default=dict)),
                ("node_explanations", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("patch_summary", models.TextField(blank=True, default="")),
                ("suggested_next_actions", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="studio.pipelinedraftsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="pipelinedraftsession",
            index=models.Index(fields=["owner", "-updated_at"], name="studio_draft_owner_upd_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinedraftsession",
            index=models.Index(fields=["source_pipeline", "-updated_at"], name="studio_draft_source_upd_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinedraftsession",
            index=models.Index(fields=["status"], name="studio_draft_status_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinedraftrevision",
            index=models.Index(fields=["session", "-created_at"], name="studio_draft_rev_session_idx"),
        ),
    ]
