# Generated by Django 6.0.7 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


def backfill_studio_projects(apps, schema_editor):
    Project = apps.get_model("core_ui", "Project")
    ProjectMembership = apps.get_model("core_ui", "ProjectMembership")
    MCPServerPool = apps.get_model("studio", "MCPServerPool")
    AgentConfig = apps.get_model("studio", "AgentConfig")
    Pipeline = apps.get_model("studio", "Pipeline")
    PipelineRun = apps.get_model("studio", "PipelineRun")
    StudioSkillAccess = apps.get_model("studio", "StudioSkillAccess")

    projects = dict(Project.objects.filter(is_default=True).values_list("owner_id", "id"))
    for model in (MCPServerPool, AgentConfig, Pipeline):
        for owner_id, project_id in projects.items():
            model.objects.filter(owner_id=owner_id, project_id__isnull=True).update(project_id=project_id)
    for owner_id, project_id in projects.items():
        StudioSkillAccess.objects.filter(owner_id=owner_id, project_id__isnull=True).update(project_id=project_id)
    pipeline_projects = dict(Pipeline.objects.values_list("id", "project_id"))
    pending_runs = []
    for run in PipelineRun.objects.filter(project_id__isnull=True).iterator(chunk_size=500):
        run.project_id = pipeline_projects.get(run.pipeline_id)
        if run.project_id:
            pending_runs.append(run)
    if pending_runs:
        PipelineRun.objects.bulk_update(pending_runs, ["project"], batch_size=500)

    for model in (MCPServerPool, AgentConfig, Pipeline, StudioSkillAccess):
        for resource in model.objects.exclude(owner_id=None).prefetch_related("shared_with").iterator(chunk_size=200):
            for user_id in resource.shared_with.values_list("id", flat=True):
                ProjectMembership.objects.get_or_create(
                    project_id=resource.project_id,
                    user_id=user_id,
                    defaults={"role": "viewer"},
                )

    Server = apps.get_model("servers", "Server")
    ServerAgent = apps.get_model("servers", "ServerAgent")
    Playbook = apps.get_model("servers", "Playbook")
    for membership in ProjectMembership.objects.filter(is_active=True, project__is_default=True).iterator(
        chunk_size=200
    ):
        default_project_id = membership.project_id
        has_resources = any(
            (
                Server.objects.filter(project_id=default_project_id).exists(),
                ServerAgent.objects.filter(project_id=default_project_id).exists(),
                Playbook.objects.filter(project_id=default_project_id).exists(),
                MCPServerPool.objects.filter(project_id=default_project_id).exists(),
                AgentConfig.objects.filter(project_id=default_project_id).exists(),
                Pipeline.objects.filter(project_id=default_project_id).exists(),
                StudioSkillAccess.objects.filter(project_id=default_project_id).exists(),
            )
        )
        if has_resources:
            continue
        team_memberships = list(
            ProjectMembership.objects.filter(user_id=membership.user_id, project__is_default=False)[:2]
        )
        if len(team_memberships) != 1:
            continue
        membership.is_active = False
        membership.save(update_fields=["is_active", "updated_at"])
        team_memberships[0].is_active = True
        team_memberships[0].save(update_fields=["is_active", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("core_ui", "0022_projects"),
        ("servers", "0052_project_tenant_boundary"),
        ("studio", "0014_approval_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserverpool",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_mcp_servers",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="agentconfig",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_agent_configs",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_pipelines",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="studioskillaccess",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_skill_access",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_pipeline_runs",
                to="core_ui.project",
            ),
        ),
        migrations.RunPython(backfill_studio_projects, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mcpserverpool",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_mcp_servers",
                to="core_ui.project",
            ),
        ),
        migrations.AlterField(
            model_name="agentconfig",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_agent_configs",
                to="core_ui.project",
            ),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_pipelines",
                to="core_ui.project",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studio_pipeline_runs",
                to="core_ui.project",
            ),
        ),
        migrations.AddIndex(
            model_name="mcpserverpool",
            index=models.Index(fields=["project", "name"], name="studio_mcps_project_33029c_idx"),
        ),
        migrations.AddIndex(
            model_name="agentconfig",
            index=models.Index(fields=["project", "-updated_at"], name="studio_agen_project_c2a26d_idx"),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(fields=["project", "-updated_at"], name="studio_pipe_project_850157_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["project", "-created_at"], name="studio_run_project_78f340_idx"),
        ),
    ]
