# Generated by Django 5.2.16 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0015_project_tenant_boundary"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="telegram_bot_token_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="telegram_chat_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="TelegramBotCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bot_token_digest", models.CharField(max_length=64, unique=True)),
                ("update_offset", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramReplyRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.CharField(max_length=100)),
                ("bot_token_digest", models.CharField(max_length=64)),
                ("chat_id", models.CharField(max_length=64)),
                ("prompt_message_id", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("received", "Received"), ("expired", "Expired")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("response_text", models.TextField(blank=True)),
                ("response_message_id", models.BigIntegerField(blank=True, null=True)),
                ("response_from", models.CharField(blank=True, default="", max_length=150)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_reply_requests",
                        to="studio.pipelinerun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="studio_tg_reply_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bot_token_digest", "chat_id", "prompt_message_id"),
                        name="studio_tg_reply_message_uniq",
                    ),
                    models.UniqueConstraint(fields=("run", "node_id"), name="studio_tg_reply_run_node_uniq"),
                ],
            },
        ),
    ]
