# Generated by Django 5.2.16 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0016_telegram_delivery_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineDispatchControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="global", max_length=32, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PipelineRunDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, max_length=120)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("error", models.TextField(blank=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch",
                        to="studio.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["queued_at", "id"],
                "indexes": [
                    models.Index(fields=["status", "queued_at"], name="studio_dispatch_status_idx"),
                    models.Index(fields=["claimed_by", "status"], name="studio_dispatch_worker_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gte", 1)),
                        name="studio_dispatch_max_attempts_gte_1",
                    ),
                ],
            },
        ),
    ]
