# Generated by Django 5.2.16 on 2026-07-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_pipelinerundispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinetrigger',
            name='signing_secret',
            field=models.CharField(blank=True, help_text='Optional HMAC-SHA256 secret used to verify webhook deliveries', max_length=255),
        ),
        migrations.CreateModel(
            name='PipelineWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=200)),
                ('body_sha256', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery', to='studio.pipelinerun')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='studio.pipelinetrigger')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['received_at'], name='studio_webhook_received_idx')],
                'constraints': [models.UniqueConstraint(fields=('trigger', 'delivery_id'), name='studio_webhook_delivery_unique')],
            },
        ),
    ]
