# Generated by Django 5.2.16 on 2026-07-30 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0018_pipelinetrigger_signing_secret_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineNodeDeadLetter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.CharField(max_length=100)),
                ("node_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")], default="open", max_length=20
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=1)),
                ("max_attempts", models.PositiveSmallIntegerField(default=1)),
                ("last_error", models.TextField(blank=True)),
                ("node_state", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_pipeline_dead_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letters",
                        to="studio.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="studio_dead_status_created_idx"),
                    models.Index(fields=["run", "status"], name="studio_dead_run_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "node_id"), name="studio_dead_letter_run_node_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gte", 1)), name="studio_dead_letter_max_gte_1"
                    ),
                ],
            },
        ),
    ]
