# Generated by Django 5.2.10 on 2026-08-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_pipelinenodedeadletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='provider_binding',
            field=models.JSONField(blank=True, default=dict, help_text='Canonical provider binding used when this agent config runs.'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='provider_binding',
            field=models.JSONField(blank=True, default=dict, help_text='Provider binding pinned when scheduled/background triggers are saved.'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='provider_binding_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='provider_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
