# Generated by Django 5.2.10 on 2026-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_agentconfig_provider_binding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='provider_execution_mode',
            field=models.CharField(default='interactive', max_length=20),
        ),
    ]
