from __future__ import annotations

from app.assistant_actions import AssistantActionSpec, register_action, register_runtime_context_provider
from studio.assistant_actions import (
    apply_pipeline_draft,
    approve_pipeline_node,
    build_assistant_runtime_context,
    capability_registry,
    create_pipeline_draft,
    list_mcp_servers,
    list_pipelines,
    list_runs,
    list_studio_skills,
    run_pipeline,
    stop_pipeline_run,
    validate_pipeline_draft,
    validate_pipeline_run,
    validate_studio_skills,
)


def register_assistant_actions() -> None:
    register_runtime_context_provider("studio", build_assistant_runtime_context)
    specs = [
        AssistantActionSpec(
            action_type="studio.pipelines.list",
            label="List Studio pipelines",
            description="List available Studio pipelines.",
            required_feature="studio_pipelines",
            risk="read",
            handler=list_pipelines,
        ),
        AssistantActionSpec(
            action_type="studio.runs.list",
            label="List Studio runs",
            description="List recent Studio pipeline runs.",
            required_feature="studio_runs",
            risk="read",
            handler=list_runs,
        ),
        AssistantActionSpec(
            action_type="studio.capabilities.registry",
            label="Show Studio capabilities",
            description="Read the Studio capability registry with matching MCP servers, skills, and task families.",
            required_feature="studio",
            risk="read",
            handler=capability_registry,
        ),
        AssistantActionSpec(
            action_type="studio.mcp.list",
            label="List Studio MCP servers",
            description="List accessible MCP servers without invoking tools.",
            required_feature="studio_mcp",
            risk="read",
            handler=list_mcp_servers,
        ),
        AssistantActionSpec(
            action_type="studio.skills.list",
            label="List Studio skills",
            description="List accessible Studio skills and their safety metadata.",
            required_feature="studio_skills",
            risk="read",
            handler=list_studio_skills,
        ),
        AssistantActionSpec(
            action_type="studio.skills.validate",
            label="Validate Studio skills",
            description="Validate accessible Studio skills without changing skill files.",
            required_feature="studio_skills",
            risk="read",
            input_schema={"optional": ["slugs", "strict"]},
            handler=validate_studio_skills,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline_draft.create",
            label="Create pipeline draft",
            description="Create a Studio pipeline AI draft from a chat request.",
            required_feature="studio_pipelines",
            risk="internal_write",
            requires_confirmation=True,
            input_schema={"required": ["pipeline_name", "user_message"]},
            handler=create_pipeline_draft,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline_draft.validate",
            label="Validate pipeline draft",
            description="Dry-run validate a Studio pipeline draft without runtime actions.",
            required_feature="studio_pipelines",
            risk="read",
            input_schema={"required": ["draft_id"]},
            handler=validate_pipeline_draft,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline_draft.apply",
            label="Apply pipeline draft",
            description="Apply a validated Studio draft to create/update a pipeline.",
            required_feature="studio_pipelines",
            risk="internal_write",
            requires_confirmation=True,
            input_schema={"required": ["draft_id"]},
            handler=apply_pipeline_draft,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.run_validate",
            label="Validate pipeline run",
            description="Validate/dry-run a manual pipeline launch without execution.",
            required_feature="studio_pipelines",
            risk="read",
            input_schema={"required": ["pipeline_id"]},
            handler=validate_pipeline_run,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.run",
            label="Run pipeline",
            description="Launch a pipeline manual trigger after validation.",
            required_feature="studio_pipelines",
            risk="mutating",
            requires_confirmation=True,
            input_schema={"required": ["pipeline_id"]},
            handler=run_pipeline,
        ),
        AssistantActionSpec(
            action_type="studio.run.stop",
            label="Stop pipeline run",
            description="Request stop for an active Studio pipeline run.",
            required_feature="studio_runs",
            risk="mutating",
            requires_confirmation=True,
            input_schema={"required": ["run_id"]},
            handler=stop_pipeline_run,
        ),
        AssistantActionSpec(
            action_type="studio.run.approve_node",
            label="Approve pipeline node",
            description="Record an approval/rejection for a waiting pipeline approval node owned by the user.",
            required_feature="studio_runs",
            risk="mutating",
            requires_confirmation=True,
            input_schema={"required": ["run_id", "node_id", "decision"]},
            handler=approve_pipeline_node,
        ),
    ]
    for spec in specs:
        register_action(spec)
