from __future__ import annotations

from app.assistant_actions import AssistantActionSpec, register_action, register_runtime_context_provider
from studio.assistant_actions import (
    apply_pipeline_draft,
    build_assistant_runtime_context,
    capability_registry,
    create_pipeline_draft,
    create_studio_skill,
    get_pipeline,
    get_studio_skill,
    list_mcp_servers,
    list_pipeline_drafts,
    list_pipelines,
    list_runs,
    list_studio_skills,
    revise_pipeline_draft,
    run_pipeline,
    stop_pipeline_run,
    update_studio_skill,
    validate_pipeline_draft,
    validate_pipeline_run,
    validate_studio_skills,
)


def register_assistant_actions() -> None:
    register_runtime_context_provider("studio", build_assistant_runtime_context)
    specs = [
        AssistantActionSpec(
            action_type="studio.pipelines.list",
            label="List Studio pipelines",
            description="List available Studio pipelines.",
            required_feature="studio_pipelines",
            risk="read",
            handler=list_pipelines,
        ),
        AssistantActionSpec(
            action_type="studio.runs.list",
            label="List Studio runs",
            description="List recent Studio pipeline runs.",
            required_feature="studio_runs",
            risk="read",
            handler=list_runs,
        ),
        AssistantActionSpec(
            action_type="studio.capabilities.registry",
            label="Show Studio capabilities",
            description="Read the Studio capability registry with matching MCP servers, skills, and task families.",
            required_feature="studio",
            risk="read",
            handler=capability_registry,
        ),
        AssistantActionSpec(
            action_type="studio.mcp.list",
            label="List Studio MCP servers",
            description="List accessible MCP servers without invoking tools.",
            required_feature="studio_mcp",
            risk="read",
            handler=list_mcp_servers,
        ),
        AssistantActionSpec(
            action_type="studio.skills.list",
            label="List Studio skills",
            description="List accessible Studio skills and their safety metadata.",
            required_feature="studio_skills",
            risk="read",
            handler=list_studio_skills,
        ),
        AssistantActionSpec(
            action_type="studio.skills.validate",
            label="Validate Studio skills",
            description="Validate accessible Studio skills without changing skill files.",
            required_feature="studio_skills",
            risk="read",
            input_schema={"optional": ["slugs", "strict"]},
            handler=validate_studio_skills,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.get",
            label="Get pipeline",
            description="Read one Studio pipeline (graph summary + detail) for edit/run planning.",
            required_feature="studio_pipelines",
            risk="read",
            input_schema={"required": ["pipeline_id"]},
            handler=get_pipeline,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.pipeline_draft.create",
            label="Create pipeline draft",
            description="Create a Studio pipeline AI draft from a chat request (natural language goal).",
            required_feature="studio_pipelines",
            risk="internal_write",
            requires_confirmation=True,
            input_schema={"required": ["pipeline_name", "user_message"]},
            handler=create_pipeline_draft,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.pipeline_draft.list",
            label="List pipeline drafts",
            description="List open Studio pipeline drafts for the operator.",
            required_feature="studio_pipelines",
            risk="read",
            handler=list_pipeline_drafts,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.pipeline_draft.revise",
            label="Revise pipeline draft",
            description="Continue configuring a draft with a natural-language instruction (add nodes, change SSH, schedule, etc.).",
            required_feature="studio_pipelines",
            risk="internal_write",
            requires_confirmation=True,
            input_schema={"required": ["draft_id", "user_message"]},
            handler=revise_pipeline_draft,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.pipeline_draft.validate",
            label="Validate pipeline draft",
            description="Dry-run validate a Studio pipeline draft without runtime actions.",
            required_feature="studio_pipelines",
            risk="read",
            input_schema={"required": ["draft_id"]},
            handler=validate_pipeline_draft,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.pipeline_draft.apply",
            label="Apply pipeline draft",
            description="Apply a validated Studio draft to create/update a pipeline.",
            required_feature="studio_pipelines",
            risk="internal_write",
            requires_confirmation=True,
            input_schema={"required": ["draft_id"]},
            handler=apply_pipeline_draft,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.run_validate",
            label="Validate pipeline run",
            description="Validate/dry-run a manual pipeline launch without execution.",
            required_feature="studio_pipelines",
            risk="read",
            input_schema={"required": ["pipeline_id"]},
            handler=validate_pipeline_run,
        ),
        AssistantActionSpec(
            action_type="studio.pipeline.run",
            label="Run pipeline",
            description="Launch a pipeline manual trigger after validation.",
            required_feature="studio_pipelines",
            risk="mutating",
            requires_confirmation=True,
            input_schema={"required": ["pipeline_id"]},
            handler=run_pipeline,
        ),
        AssistantActionSpec(
            action_type="studio.run.stop",
            label="Stop pipeline run",
            description="Request stop for an active Studio pipeline run.",
            required_feature="studio_runs",
            risk="mutating",
            requires_confirmation=True,
            input_schema={"required": ["run_id"]},
            handler=stop_pipeline_run,
        ),
        AssistantActionSpec(
            action_type="studio.skills.get",
            label="Get Studio skill",
            description="Read one Studio skill (metadata + body) the operator can access.",
            required_feature="studio_skills",
            risk="read",
            input_schema={"required": ["slug"]},
            handler=get_studio_skill,
        ),
        AssistantActionSpec(
            action_type="studio.skills.create",
            label="Create Studio skill",
            description="Scaffold a new Studio skill for the operator (name, description, optional body).",
            required_feature="studio_skills",
            risk="internal_write",
            requires_confirmation=True,
            input_schema={"required": ["name", "description"]},
            handler=create_studio_skill,
        ),
        AssistantActionSpec(
            action_type="studio.skills.update",
            label="Update Studio skill",
            description="Edit an owned Studio skill metadata and/or SKILL.md body content.",
            required_feature="studio_skills",
            risk="internal_write",
            requires_confirmation=True,
            input_schema={"required": ["slug"]},
            handler=update_studio_skill,
        ),
    ]
    for spec in specs:
        register_action(spec)
