from __future__ import annotations

from .node_manifest_common import (
    ON_FAILURE_SCHEMA,
    SERVER_ID_FIELDS,
    NodeManifest,
    _array,
    _bool,
    _int,
    _manifest,
    _obj,
    _schema,
    _str,
)

OPS_NODE_MANIFESTS: dict[str, NodeManifest] = {
    "ops/server_snapshot": _manifest(
        "ops/server_snapshot",
        "Ops",
        "Structured read-only Linux server snapshot from existing WebTerm Linux UI collectors.",
        ("success", "error", "out"),
        risk_level="read_only",
        tags=("linux", "diagnostics", "snapshot"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "sections": _array(
                    _str(enum=("overview", "services", "processes", "docker", "logs", "disk", "network", "packages")),
                    default=["overview", "services", "docker", "disk"],
                ),
                "log_source": _str(default="journal"),
                "service": _str(description="Optional service name for log sections."),
                "lines": _int(minimum=20, maximum=240, default=80),
                "limit": _int(minimum=1, maximum=500, default=80),
                "on_failure": ON_FAILURE_SCHEMA,
            }
        ),
        output_schema=_schema({"output": _str(), "snapshot": _obj()}),
    ),
    "ops/log_query": _manifest(
        "ops/log_query",
        "Ops",
        "Read-only Linux/service/Docker log collection with optional text filtering.",
        ("success", "error", "out"),
        risk_level="read_only",
        tags=("linux", "logs", "diagnostics", "incident"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "source": _str(
                    enum=(
                        "journal",
                        "service",
                        "docker",
                        "syslog",
                        "messages",
                        "auth",
                        "nginx_error",
                        "nginx_access",
                        "apache_error",
                        "apache_access",
                    ),
                    default="journal",
                ),
                "service": _str(description="Required when source=service."),
                "container": _str(description="Required when source=docker."),
                "lines": _int(minimum=20, maximum=240, default=120),
                "filter_text": _str(description="Optional case-insensitive substring filter."),
                "on_failure": ON_FAILURE_SCHEMA,
            }
        ),
        output_schema=_schema({"output": _str(), "logs": _obj()}),
    ),
    "ops/file_action": _manifest(
        "ops/file_action",
        "Ops",
        "Read or write UTF-8 text files over the existing SFTP layer.",
        ("success", "error", "out"),
        risk_level="dynamic",
        mutates_state=True,
        supports_dry_run=True,
        requires_approval_by_default=True,
        recommended_verification=("ops/file_action", "output/report"),
        tags=("linux", "file", "config"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "action": _str(enum=("read", "write"), default="read"),
                "path": _str(description="Remote text file path."),
                "content": _str(description="UTF-8 content for write action. Supports templates."),
                "allow_empty_content": _bool(default=False),
                "max_bytes": _int(minimum=1024, maximum=1048576, default=131072),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("path", "action"),
        ),
        output_schema=_schema({"output": _str(), "file": _obj()}),
    ),
    "ops/package_action": _manifest(
        "ops/package_action",
        "Ops",
        "List package updates or run explicit package install/update/remove actions.",
        ("success", "error", "out"),
        risk_level="dynamic",
        mutates_state=True,
        supports_dry_run=True,
        requires_approval_by_default=True,
        recommended_verification=("ops/package_action", "ops/server_snapshot", "output/report"),
        tags=("linux", "packages", "maintenance"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "action": _str(enum=("list_updates", "install", "update", "remove"), default="list_updates"),
                "packages": _array(_str(), description="Explicit package names for install/update/remove."),
                "verify": _bool(default=True),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("action",),
        ),
        output_schema=_schema({"output": _str(), "packages": _obj(), "package_action": _obj()}),
    ),
    "ops/disk_cleanup": _manifest(
        "ops/disk_cleanup",
        "Ops",
        "Inspect disk usage or run bounded journal/tmp cleanup actions.",
        ("success", "error", "out"),
        risk_level="dynamic",
        mutates_state=True,
        supports_dry_run=True,
        requires_approval_by_default=True,
        recommended_verification=("ops/disk_cleanup", "ops/server_snapshot", "output/report"),
        tags=("linux", "disk", "cleanup", "maintenance"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "action": _str(enum=("inspect", "journal_vacuum", "tmp_cleanup"), default="inspect"),
                "dry_run": _bool(default=False),
                "verify": _bool(default=True),
                "min_age_days": _int(minimum=1, maximum=365, default=7),
                "max_entries": _int(minimum=1, maximum=500, default=50),
                "vacuum_time_days": _int(minimum=1, maximum=365, default=14),
                "vacuum_size_mb": _int(minimum=64, maximum=102400),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("action",),
        ),
        output_schema=_schema({"output": _str(), "disk": _obj(), "disk_cleanup": _obj()}),
    ),
    "ops/backup_restore_check": _manifest(
        "ops/backup_restore_check",
        "Ops",
        "Read-only backup freshness and latest archive integrity check.",
        ("success", "error", "out"),
        risk_level="read_only",
        supports_dry_run=True,
        recommended_verification=("ops/backup_restore_check", "output/report"),
        tags=("linux", "backup", "restore", "verification"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "action": _str(enum=("inspect", "verify_latest"), default="inspect"),
                "path": _str(description="Remote backup directory path."),
                "max_depth": _int(minimum=1, maximum=5, default=2),
                "max_files": _int(minimum=1, maximum=100, default=20),
                "max_age_hours": _int(minimum=1, maximum=8760, default=24),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("action", "path"),
        ),
        output_schema=_schema({"output": _str(), "backup_restore_check": _obj()}),
    ),
    "ops/service_action": _manifest(
        "ops/service_action",
        "Ops",
        "Structured systemd service action with preflight and verification.",
        ("success", "error", "out"),
        risk_level="mutating",
        mutates_state=True,
        supports_dry_run=True,
        requires_approval_by_default=True,
        recommended_verification=("ops/server_snapshot", "ops/http_check"),
        tags=("linux", "systemd", "service"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "service": _str(description="systemd service name. Falls back to service_name runtime context when empty."),
                "action": _str(enum=("start", "stop", "restart", "reload"), default="restart"),
                "verify": _bool(default=True),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("service", "action"),
        ),
        output_schema=_schema({"output": _str(), "action_result": _obj()}),
    ),
    "ops/docker_action": _manifest(
        "ops/docker_action",
        "Ops",
        "Structured Docker container start/stop/restart with inspect/log verification.",
        ("success", "error", "out"),
        risk_level="mutating",
        mutates_state=True,
        supports_dry_run=True,
        requires_approval_by_default=True,
        recommended_verification=("ops/server_snapshot", "ops/http_check"),
        tags=("docker", "container"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "container": _str(description="Docker container name or id."),
                "action": _str(enum=("start", "stop", "restart"), default="restart"),
                "include_logs": _bool(default=True),
                "verify": _bool(default=True),
                "lines": _int(minimum=20, maximum=240, default=80),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("container", "action"),
        ),
        output_schema=_schema({"output": _str(), "action_result": _obj()}),
    ),
    "ops/process_action": _manifest(
        "ops/process_action",
        "Ops",
        "Structured process terminate/kill action on a target server.",
        ("success", "error", "out"),
        risk_level="dangerous",
        mutates_state=True,
        supports_dry_run=True,
        requires_approval_by_default=True,
        recommended_verification=("ops/server_snapshot",),
        tags=("linux", "process", "break-glass"),
        input_schema=_schema(
            {
                **SERVER_ID_FIELDS,
                "pid": _int(description="Explicit process id."),
                "pid_context_key": _str(default="pid", description="Context key to resolve PID from."),
                "action": _str(enum=("terminate", "kill_force"), default="terminate"),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("action",),
        ),
        output_schema=_schema({"output": _str(), "action_result": _obj()}),
    ),
    "ops/http_check": _manifest(
        "ops/http_check",
        "Ops",
        "HTTP availability/content check with retries and expected statuses.",
        ("success", "error", "out"),
        risk_level="read_only",
        tags=("http", "health", "verification"),
        input_schema=_schema(
            {
                "url": _str(description="URL template to check."),
                "method": _str(enum=("GET", "HEAD"), default="GET"),
                "expected_status": _array(_int(minimum=100, maximum=599), default=[200]),
                "timeout_seconds": _int(minimum=1, maximum=120, default=15),
                "retries": _int(minimum=1, maximum=5, default=1),
                "body_contains": _str(description="Optional response body substring."),
                "on_failure": ON_FAILURE_SCHEMA,
            },
            required=("url",),
        ),
        output_schema=_schema({"output": _str(), "http_check": _obj()}),
    ),
    "ops/alert_update": _manifest(
        "ops/alert_update",
        "Ops",
        "Update a WebTerm monitoring alert, currently resolve-by-id.",
        ("success", "error", "out"),
        risk_level="mutating",
        mutates_state=True,
        tags=("monitoring", "alert"),
        input_schema=_schema(
            {
                "alert_id": _int(description="Explicit monitoring alert id."),
                "alert_id_context_key": _str(default="alert_id", description="Context key to resolve alert_id from."),
                "action": _str(enum=("resolve",), default="resolve"),
                "note": _str(description="Operator note stored in output."),
                "on_failure": ON_FAILURE_SCHEMA,
            }
        ),
        output_schema=_schema({"output": _str(), "alert": _obj()}),
    ),
}
