# Generated by Django 5.2.10 on 2026-04-08 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_agentrunevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMemoryEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_kind', models.CharField(choices=[('terminal_session', 'Terminal Session'), ('agent_investigation', 'Agent Investigation'), ('deploy_operation', 'Deploy Operation'), ('incident', 'Incident'), ('monitoring_window', 'Monitoring Window'), ('rdp_session', 'RDP Session'), ('pipeline_operation', 'Pipeline Operation'), ('misc', 'Misc')], default='misc', max_length=40)),
                ('source_kind', models.CharField(blank=True, max_length=30)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('event_count', models.IntegerField(default=0)),
                ('importance_score', models.FloatField(default=0.5)),
                ('confidence', models.FloatField(default=0.7)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_event_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerMemoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('terminal', 'Terminal'), ('agent_run', 'Agent Run'), ('agent_event', 'Agent Event'), ('monitoring', 'Monitoring'), ('watcher', 'Watcher'), ('pipeline', 'Pipeline'), ('rdp', 'RDP'), ('manual_knowledge', 'Manual Knowledge'), ('system', 'System')], max_length=30)),
                ('actor_kind', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('watcher', 'Watcher'), ('system', 'System')], default='system', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('raw_text_redacted', models.TextField(blank=True)),
                ('structured_payload', models.JSONField(blank=True, default=dict)),
                ('importance_hint', models.FloatField(default=0.5)),
                ('redaction_report', models.JSONField(blank=True, default=dict)),
                ('redaction_hashes', models.JSONField(blank=True, default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerMemoryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_mode', models.CharField(choices=[('heuristic', 'Heuristic'), ('nightly_llm', 'Nightly LLM'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('nightly_model_alias', models.CharField(default='opssummary', max_length=50)),
                ('nearline_event_threshold', models.IntegerField(default=6)),
                ('sleep_start_hour', models.IntegerField(default=1)),
                ('sleep_end_hour', models.IntegerField(default=5)),
                ('raw_event_retention_days', models.IntegerField(default=30)),
                ('episode_retention_days', models.IntegerField(default=90)),
                ('allow_sensitive_raw', models.BooleanField(default=False)),
                ('rdp_semantic_capture_enabled', models.BooleanField(default=False)),
                ('human_habits_capture_enabled', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='ServerMemoryRevalidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('superseded', 'Superseded')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerMemorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_key', models.CharField(max_length=80)),
                ('layer', models.CharField(choices=[('canonical', 'Canonical'), ('archive', 'Archive')], default='canonical', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_kind', models.CharField(blank=True, max_length=30)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('version_group_id', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('importance_score', models.FloatField(default=0.5)),
                ('stability_score', models.FloatField(default=0.5)),
                ('confidence', models.FloatField(default=0.7)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['memory_key', '-version', '-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='agentrunevent',
            new_name='servers_age_run_id_5b5cd7_idx',
            old_name='servers_age_run_id_5d9331_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrunevent',
            new_name='servers_age_event_t_0cff98_idx',
            old_name='servers_age_event_t_57c2a0_idx',
        ),
        migrations.AddField(
            model_name='servercommandhistory',
            name='actor_kind',
            field=models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('pipeline', 'Pipeline'), ('system', 'System')], default='human', max_length=20),
        ),
        migrations.AddField(
            model_name='servercommandhistory',
            name='cwd',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servercommandhistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servercommandhistory',
            name='source_kind',
            field=models.CharField(choices=[('terminal', 'Terminal'), ('agent', 'Agent'), ('pipeline', 'Pipeline'), ('api', 'API'), ('system', 'System')], default='terminal', max_length=20),
        ),
        migrations.AddField(
            model_name='servermemoryepisode',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_episodes', to='servers.server'),
        ),
        migrations.AddField(
            model_name='servermemoryevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_memory_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servermemoryevent',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='servers.server'),
        ),
        migrations.AddField(
            model_name='servermemorypolicy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_memory_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servermemoryrevalidation',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_revalidations', to='servers.server'),
        ),
        migrations.AddField(
            model_name='servermemorysnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_memory_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servermemorysnapshot',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='servers.server'),
        ),
        migrations.AddField(
            model_name='servermemorysnapshot',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_snapshots', to='servers.servermemorysnapshot'),
        ),
        migrations.AddField(
            model_name='servermemoryrevalidation',
            name='source_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revalidation_items', to='servers.servermemorysnapshot'),
        ),
        migrations.AddIndex(
            model_name='servermemoryepisode',
            index=models.Index(fields=['server', 'is_active', '-last_event_at'], name='servers_ser_server__7cec37_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryepisode',
            index=models.Index(fields=['server', 'episode_kind', 'is_active', '-last_event_at'], name='servers_ser_server__427e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryepisode',
            index=models.Index(fields=['server', 'session_id', '-last_event_at'], name='servers_ser_server__c98169_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryepisode',
            index=models.Index(fields=['server', 'source_ref', '-last_event_at'], name='servers_ser_server__e305f9_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryevent',
            index=models.Index(fields=['server', '-created_at'], name='servers_ser_server__b2f0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryevent',
            index=models.Index(fields=['server', 'source_kind', '-created_at'], name='servers_ser_server__12fd28_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryevent',
            index=models.Index(fields=['server', 'session_id', '-created_at'], name='servers_ser_server__63b04a_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryevent',
            index=models.Index(fields=['server', 'source_ref', '-created_at'], name='servers_ser_server__768c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemorysnapshot',
            index=models.Index(fields=['server', 'memory_key', 'is_active', '-updated_at'], name='servers_ser_server__5bef33_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemorysnapshot',
            index=models.Index(fields=['server', 'layer', '-updated_at'], name='servers_ser_server__c28d12_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemorysnapshot',
            index=models.Index(fields=['server', 'version_group_id', '-version'], name='servers_ser_server__49e12f_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryrevalidation',
            index=models.Index(fields=['server', 'status', '-updated_at'], name='servers_ser_server__bb3977_idx'),
        ),
        migrations.AddIndex(
            model_name='servermemoryrevalidation',
            index=models.Index(fields=['server', 'memory_key', 'status'], name='servers_ser_server__bed990_idx'),
        ),
    ]
