# Generated by Django 5.2.10 on 2026-04-08 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_servermemoryepisode_servermemoryevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundWorkerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_kind', models.CharField(choices=[('memory_dreams', 'Memory Dreams'), ('agent_execution', 'Agent Execution'), ('watchers', 'Watchers')], max_length=40)),
                ('worker_key', models.CharField(default='default', max_length=80)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('error', 'Error'), ('stopped', 'Stopped')], default='idle', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('command', models.CharField(blank=True, max_length=255)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_cycle_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_summary', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['worker_kind', 'worker_key'],
                'indexes': [models.Index(fields=['worker_kind', 'worker_key'], name='servers_bac_worker__57fdca_idx'), models.Index(fields=['worker_kind', 'status', '-heartbeat_at'], name='servers_bac_worker__3cbfc5_idx')],
                'unique_together': {('worker_kind', 'worker_key')},
            },
        ),
        migrations.CreateModel(
            name='AgentRunDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_kind', models.CharField(choices=[('launch', 'Initial Launch'), ('plan_execution', 'Plan Execution')], default='launch', max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('server_ids', models.JSONField(blank=True, default=list)),
                ('plan_only', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=120)),
                ('attempt_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='servers.serveragent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='servers.agentrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queued_at', 'id'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='servers_age_status_d07d60_idx'), models.Index(fields=['run', 'status', '-queued_at'], name='servers_age_run_id_5d43aa_idx'), models.Index(fields=['agent', 'status', '-queued_at'], name='servers_age_agent_i_4f1f90_idx')],
            },
        ),
    ]
