# Generated by Django 5.2.10 on 2026-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0022_backgroundworkerstate_agentrundispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveragent',
            name='memory_policy_override',
            field=models.JSONField(blank=True, default=dict, help_text='Per-agent memory policy overrides. Supported keys: nearline_event_threshold (int), dream_mode (str: heuristic|nightly_llm|hybrid), raw_event_retention_days (int), episode_retention_days (int), rdp_semantic_capture_enabled (bool), human_habits_capture_enabled (bool), is_enabled (bool). Empty dict = use user-level policy.'),
        ),
    ]
