# Generated by Django 5.2.10 on 2026-04-16 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0023_add_memory_policy_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servergroupknowledge',
            index=models.Index(fields=['group', '-updated_at'], name='servers_ser_group_i_5020c5_idx'),
        ),
        migrations.AddIndex(
            model_name='servergroupmember',
            index=models.Index(fields=['group', 'user'], name='servers_ser_group_i_d3444a_idx'),
        ),
        migrations.AddIndex(
            model_name='servergroupmember',
            index=models.Index(fields=['user'], name='servers_ser_user_id_6a3433_idx'),
        ),
        migrations.AddIndex(
            model_name='servergrouppermission',
            index=models.Index(fields=['group'], name='servers_ser_group_i_3f84f9_idx'),
        ),
        migrations.AddIndex(
            model_name='servergrouppermission',
            index=models.Index(fields=['user'], name='servers_ser_user_id_69d62e_idx'),
        ),
        migrations.AddIndex(
            model_name='servergroupsubscription',
            index=models.Index(fields=['user', 'kind'], name='servers_ser_user_id_1706d9_idx'),
        ),
    ]
