# Generated by Django 5.2.10 on 2026-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0025_add_terminal_ai_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ai_read_only',
            field=models.BooleanField(default=False, help_text='AI-агент может только читать состояние сервера, но не выполнять изменяющие команды.'),
        ),
    ]
