# Generated by Django 5.2.10 on 2026-04-17 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0026_add_server_ai_read_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(help_text='Shell command that triggered the snapshot')),
                ('file_path', models.CharField(help_text='Absolute path on remote server', max_length=1024)),
                ('content', models.TextField(blank=True, help_text='File content before modification')),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hex digest for dedup / integrity', max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0, help_text='Original file size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_snapshots', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['server', '-created_at'], name='servers_com_server__338e9e_idx'), models.Index(fields=['user', '-created_at'], name='servers_com_user_id_4cbf19_idx'), models.Index(fields=['server', 'file_path', '-created_at'], name='servers_com_server__37cf1f_idx')],
            },
        ),
    ]
