# Generated by Django 6.0.5 on 2026-06-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0029_server_detected_os_attempted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servershare',
            name='can_connect_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servershare',
            name='can_execute_command',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servershare',
            name='can_read_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servershare',
            name='can_use_rdp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servershare',
            name='can_write_files',
            field=models.BooleanField(default=False),
        ),
    ]
