# Generated by Django 6.0.5 on 2026-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0030_servershare_can_connect_terminal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermemorypolicy',
            name='rdp_semantic_capture_enabled',
        ),
        migrations.RemoveField(
            model_name='servershare',
            name='can_use_rdp',
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ssh', 'SSH (Linux)')], default='ssh', help_text='SSH-сервер Linux', max_length=10),
        ),
        migrations.AlterField(
            model_name='serveragent',
            name='memory_policy_override',
            field=models.JSONField(blank=True, default=dict, help_text='Per-agent memory policy overrides. Supported keys: nearline_event_threshold (int), dream_mode (str: heuristic|nightly_llm|hybrid), raw_event_retention_days (int), episode_retention_days (int), human_habits_capture_enabled (bool), is_enabled (bool). Empty dict = use user-level policy.'),
        ),
        migrations.AlterField(
            model_name='servermemoryepisode',
            name='episode_kind',
            field=models.CharField(choices=[('terminal_session', 'Terminal Session'), ('agent_investigation', 'Agent Investigation'), ('deploy_operation', 'Deploy Operation'), ('incident', 'Incident'), ('monitoring_window', 'Monitoring Window'), ('pipeline_operation', 'Pipeline Operation'), ('misc', 'Misc')], default='misc', max_length=40),
        ),
        migrations.AlterField(
            model_name='servermemoryevent',
            name='source_kind',
            field=models.CharField(choices=[('terminal', 'Terminal'), ('agent_run', 'Agent Run'), ('agent_event', 'Agent Event'), ('monitoring', 'Monitoring'), ('watcher', 'Watcher'), ('pipeline', 'Pipeline'), ('manual_knowledge', 'Manual Knowledge'), ('system', 'System')], max_length=30),
        ),
    ]
