# Generated by Django 6.0.5 on 2026-06-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0035_agentrun_report_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='duration_ms',
            field=models.BigIntegerField(default=0),
        ),
    ]
