# Generated by Django 6.0.5 on 2026-06-21 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0036_alter_agentrun_duration_ms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(default='JSON', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=120)),
                ('content', models.TextField(blank=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='servers.agentrun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_run_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['run', 'artifact_key'], name='servers_age_run_id_3cd146_idx'), models.Index(fields=['user', '-created_at'], name='servers_age_user_id_b5ee54_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'artifact_key'), name='uniq_agent_run_artifact_key')],
            },
        ),
    ]
