# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0037_agent_run_artifacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundworkerstate",
            name="worker_kind",
            field=models.CharField(
                choices=[
                    ("memory_dreams", "Memory Dreams"),
                    ("agent_execution", "Agent Execution"),
                    ("scheduled_agents", "Scheduled Agents"),
                    ("watchers", "Watchers"),
                ],
                max_length=40,
            ),
        ),
    ]
