# Generated by Django 5.2.10 on 2026-07-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0041_playbookrun_live_progress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playbook',
            new_name='servers_pla_user_id_46860e_idx',
            old_name='servers_pla_user_id_7c0d0a_idx',
        ),
        migrations.RenameIndex(
            model_name='playbook',
            new_name='servers_pla_user_id_61c85f_idx',
            old_name='servers_pla_user_id_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='playbook',
            new_name='servers_pla_visibil_20526b_idx',
            old_name='servers_pla_visib_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='playbookrun',
            new_name='servers_pla_user_id_e95de7_idx',
            old_name='servers_pr_user_id_crt_idx',
        ),
        migrations.RenameIndex(
            model_name='playbookrun',
            new_name='servers_pla_status_bd8d55_idx',
            old_name='servers_pr_status_crt_idx',
        ),
        migrations.RenameIndex(
            model_name='playbookrun',
            new_name='servers_pla_playboo_c790fa_idx',
            old_name='servers_pr_pb_crt_idx',
        ),
        migrations.AlterField(
            model_name='serveragent',
            name='max_iterations',
            field=models.IntegerField(default=40, help_text='Max ReAct loop iterations (1-100)'),
        ),
        migrations.AlterField(
            model_name='serveragent',
            name='session_timeout_seconds',
            field=models.IntegerField(default=1200, help_text='Max session duration in seconds'),
        ),
    ]
