# Generated by Django 5.2.10 on 2026-07-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0042_rename_servers_pla_user_id_7c0d0a_idx_servers_pla_user_id_46860e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('listen', 'Listening port')], default='listen', max_length=20)),
                ('port', models.IntegerField()),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField(blank=True)),
                ('issuer', models.TextField(blank=True)),
                ('serial', models.CharField(blank=True, max_length=128)),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=128)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('sans', models.JSONField(blank=True, default=list)),
                ('previous_fingerprint', models.CharField(blank=True, max_length=128)),
                ('fingerprint_changed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='servers.server')),
            ],
            options={
                'ordering': ['not_after'],
                'indexes': [models.Index(fields=['server', 'is_active'], name='servers_ser_server__403b33_idx'), models.Index(fields=['is_active', 'not_after'], name='servers_ser_is_acti_dc1395_idx')],
                'constraints': [models.UniqueConstraint(fields=('server', 'source', 'port'), name='uniq_server_certificate_source_port')],
            },
        ),
        migrations.CreateModel(
            name='ServerMetricRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=120)),
                ('granularity', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day')], max_length=10)),
                ('bucket_start', models.DateTimeField()),
                ('value_min', models.FloatField()),
                ('value_avg', models.FloatField()),
                ('value_max', models.FloatField()),
                ('value_last', models.FloatField()),
                ('sample_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_rollups', to='servers.server')),
            ],
            options={
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['server', 'metric_key', 'granularity', '-bucket_start'], name='servers_ser_server__ad8b6d_idx'), models.Index(fields=['granularity', 'bucket_start'], name='servers_ser_granula_ab54cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('server', 'metric_key', 'granularity', 'bucket_start'), name='uniq_server_metric_rollup_bucket')],
            },
        ),
        migrations.CreateModel(
            name='ServerMetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('quick', 'Quick check'), ('deep', 'Deep check')], default='quick', max_length=10)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('cpu_iowait_percent', models.FloatField(blank=True, null=True)),
                ('cpu_steal_percent', models.FloatField(blank=True, null=True)),
                ('cpu_count', models.IntegerField(blank=True, null=True)),
                ('load_1m', models.FloatField(blank=True, null=True)),
                ('load_5m', models.FloatField(blank=True, null=True)),
                ('load_15m', models.FloatField(blank=True, null=True)),
                ('memory_total_mb', models.IntegerField(blank=True, null=True)),
                ('memory_available_mb', models.IntegerField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('swap_total_mb', models.IntegerField(blank=True, null=True)),
                ('swap_used_mb', models.IntegerField(blank=True, null=True)),
                ('swap_percent', models.FloatField(blank=True, null=True)),
                ('disk_mounts', models.JSONField(blank=True, default=list)),
                ('net_rx_bps', models.FloatField(blank=True, null=True)),
                ('net_tx_bps', models.FloatField(blank=True, null=True)),
                ('net_errors_per_sec', models.FloatField(blank=True, null=True)),
                ('tcp_retrans_per_sec', models.FloatField(blank=True, null=True)),
                ('tcp_established', models.IntegerField(blank=True, null=True)),
                ('fd_used', models.BigIntegerField(blank=True, null=True)),
                ('fd_max', models.BigIntegerField(blank=True, null=True)),
                ('process_count', models.IntegerField(blank=True, null=True)),
                ('zombie_count', models.IntegerField(blank=True, null=True)),
                ('top_processes', models.JSONField(blank=True, default=dict)),
                ('journal_err_10m', models.IntegerField(blank=True, null=True)),
                ('journal_warn_10m', models.IntegerField(blank=True, null=True)),
                ('reboot_required', models.BooleanField(blank=True, null=True)),
                ('ntp_synchronized', models.BooleanField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='servers.server')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['server', '-collected_at'], name='servers_ser_server__0967ba_idx')],
            },
        ),
    ]
