# Generated by Django 5.2.10 on 2026-07-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0043_metrics_timeseries_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('server', 'Server'), ('fleet', 'Fleet')], default='server', max_length=10)),
                ('endpoint_key', models.CharField(blank=True, db_index=True, max_length=270)),
                ('verdict', models.CharField(choices=[('low', 'Low risk'), ('medium', 'Medium risk'), ('high', 'High risk'), ('critical', 'Critical risk'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('context_fingerprint', models.CharField(blank=True, max_length=64)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'endpoint_key', '-created_at'], name='servers_ser_kind_9acb0b_idx'), models.Index(fields=['server', '-created_at'], name='servers_ser_server__ac6f75_idx')],
            },
        ),
    ]
