# Generated by Django 6.0.7 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


def backfill_server_projects(apps, schema_editor):
    Project = apps.get_model("core_ui", "Project")
    ProjectMembership = apps.get_model("core_ui", "ProjectMembership")
    Server = apps.get_model("servers", "Server")
    ServerAgent = apps.get_model("servers", "ServerAgent")
    AgentRun = apps.get_model("servers", "AgentRun")
    ServerShare = apps.get_model("servers", "ServerShare")
    Playbook = apps.get_model("servers", "Playbook")
    PlaybookGrant = apps.get_model("servers", "PlaybookGrant")
    PlaybookRun = apps.get_model("servers", "PlaybookRun")
    User = apps.get_model("auth", "User")

    projects = dict(Project.objects.filter(is_default=True).values_list("owner_id", "id"))
    for model in (Server, ServerAgent, Playbook):
        for owner_id, project_id in projects.items():
            model.objects.filter(**{"user_id": owner_id, "project_id__isnull": True}).update(project_id=project_id)

    for share in ServerShare.objects.select_related("server").iterator(chunk_size=500):
        operational = any(
            (
                share.can_connect_terminal,
                share.can_execute_command,
                share.can_read_files,
                share.can_write_files,
            )
        )
        role = "operator" if operational else "viewer"
        membership, created = ProjectMembership.objects.get_or_create(
            project_id=share.server.project_id,
            user_id=share.user_id,
            defaults={"role": role},
        )
        if not created and operational and membership.role == "viewer":
            membership.role = "operator"
            membership.save(update_fields=["role", "updated_at"])

    for grant in PlaybookGrant.objects.select_related("playbook", "user", "group").iterator(chunk_size=200):
        if grant.user_id:
            users = [grant.user]
        elif grant.group_id:
            users = list(grant.group.user_set.filter(is_active=True))
        elif grant.workspace_shared:
            users = list(User.objects.filter(is_active=True).exclude(pk=grant.playbook.user_id))
        else:
            users = []
        role = "viewer" if grant.role == "viewer" else "operator"
        for user in users:
            membership, created = ProjectMembership.objects.get_or_create(
                project_id=grant.playbook.project_id,
                user_id=user.id,
                defaults={"role": role},
            )
            if not created and role == "operator" and membership.role == "viewer":
                membership.role = "operator"
                membership.save(update_fields=["role", "updated_at"])

    agent_projects = dict(ServerAgent.objects.values_list("id", "project_id"))
    server_projects = dict(Server.objects.values_list("id", "project_id"))
    pending_agent_runs = []
    for run in AgentRun.objects.filter(project_id__isnull=True).iterator(chunk_size=500):
        run.project_id = (
            agent_projects.get(run.agent_id)
            or server_projects.get(run.server_id)
            or projects.get(run.user_id)
        )
        if run.project_id:
            pending_agent_runs.append(run)
    if pending_agent_runs:
        AgentRun.objects.bulk_update(pending_agent_runs, ["project"], batch_size=500)

    playbook_projects = dict(Playbook.objects.values_list("id", "project_id"))
    pending_playbook_runs = []
    for run in PlaybookRun.objects.filter(project_id__isnull=True).iterator(chunk_size=500):
        run.project_id = playbook_projects.get(run.playbook_id) or projects.get(run.user_id)
        if run.project_id:
            pending_playbook_runs.append(run)
    if pending_playbook_runs:
        PlaybookRun.objects.bulk_update(pending_playbook_runs, ["project"], batch_size=500)

    through = ServerAgent.servers.through
    invalid_ids = through.objects.exclude(serveragent__project_id=models.F("server__project_id")).values_list(
        "id", flat=True
    )
    through.objects.filter(id__in=invalid_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core_ui", "0022_projects"),
        ("servers", "0051_agent_run_event_integrity"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servers",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="serveragent",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_agents",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="playbook",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbooks",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_runs",
                to="core_ui.project",
            ),
        ),
        migrations.AddField(
            model_name="playbookrun",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbook_runs",
                to="core_ui.project",
            ),
        ),
        migrations.RunPython(backfill_server_projects, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="server",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servers",
                to="core_ui.project",
            ),
        ),
        migrations.AlterField(
            model_name="serveragent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_agents",
                to="core_ui.project",
            ),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbooks",
                to="core_ui.project",
            ),
        ),
        migrations.AlterField(
            model_name="playbookrun",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbook_runs",
                to="core_ui.project",
            ),
        ),
        migrations.AddIndex(
            model_name="server",
            index=models.Index(fields=["project", "-updated_at"], name="servers_ser_project_7c37ec_idx"),
        ),
        migrations.AddIndex(
            model_name="serveragent",
            index=models.Index(fields=["project", "-updated_at"], name="servers_ser_project_5fd502_idx"),
        ),
        migrations.AddIndex(
            model_name="playbook",
            index=models.Index(fields=["project", "-updated_at"], name="servers_pla_project_0f003a_idx"),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(fields=["project", "-started_at"], name="servers_run_project_ae7621_idx"),
        ),
        migrations.AddIndex(
            model_name="playbookrun",
            index=models.Index(fields=["project", "-created_at"], name="servers_pbr_project_1a80ab_idx"),
        ),
    ]
