# Generated by Django 5.2.16 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers", "0052_project_tenant_boundary"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandsnapshot",
            name="content_truncated",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Stored content was truncated at COMMAND_SNAPSHOT_MAX_CONTENT_BYTES "
                    "and cannot be restored safely"
                ),
            ),
        ),
    ]
