# Generated by Django 5.2.16 on 2026-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0053_commandsnapshot_content_truncated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='encrypted_password',
            field=models.TextField(blank=True, editable=False, help_text='DEPRECATED: migration-only field; remove in the next schema cleanup migration'),
        ),
        migrations.AlterField(
            model_name='server',
            name='encrypted_sudo_password',
            field=models.TextField(blank=True, editable=False, help_text='DEPRECATED: migration-only field; remove in the next schema cleanup migration'),
        ),
        migrations.AlterField(
            model_name='server',
            name='salt',
            field=models.BinaryField(blank=True, help_text='DEPRECATED: migration-only field; remove in the next schema cleanup migration', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='sudo_salt',
            field=models.BinaryField(blank=True, help_text='DEPRECATED: migration-only field; remove in the next schema cleanup migration', null=True),
        ),
    ]
