# Generated by Django 5.2.16 on 2026-07-30 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0023_operatorturndispatch'),
        ('servers', '0054_alter_server_encrypted_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerBulkOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('set_active', 'Set active state'), ('set_ai_read_only', 'Set AI read-only state'), ('set_tags', 'Replace tags')], max_length=32)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('target_server_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('claimed_by', models.CharField(blank=True, max_length=160)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operations', to='servers.servergroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_bulk_operations', to='core_ui.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_server_bulk_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'lease_expires_at'], name='srv_bulk_status_lease_idx'), models.Index(fields=['group', '-created_at'], name='srv_bulk_group_created_idx'), models.Index(fields=['project', 'status'], name='srv_bulk_project_status_idx')],
            },
        ),
    ]
