# Generated by Django 5.2.16 on 2026-07-31 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0055_serverbulkoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commandsnapshot',
            index=models.Index(fields=['created_at'], name='srv_snapshot_created_idx'),
        ),
        migrations.AddIndex(
            model_name='servercommandhistory',
            index=models.Index(fields=['executed_at'], name='srv_cmdhist_executed_idx'),
        ),
        migrations.AddIndex(
            model_name='serverhealthcheck',
            index=models.Index(fields=['checked_at'], name='srv_health_checked_idx'),
        ),
    ]
