# Generated by Django 5.2.10 on 2026-08-11 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0058_agentdispatchcontrol_and_dispatch_capacity_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='provider_binding_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='provider_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serveragent',
            name='provider_binding',
            field=models.JSONField(blank=True, default=dict, help_text='Canonical provider binding pinned for this agent and its scheduled runs.'),
        ),
        migrations.CreateModel(
            name='TerminalAiProviderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_binding', models.JSONField(blank=True, default=dict)),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_ai_provider_states', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_ai_provider_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'server'], name='servers_ter_user_id_4d43a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'server'), name='servers_terminal_ai_provider_unique')],
            },
        ),
    ]
