# Generated by Django 5.2.10 on 2026-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0059_agentrun_provider_binding_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='provider_execution_mode',
            field=models.CharField(default='interactive', max_length=20),
        ),
    ]
