apiVersion: 1

deleteDatasources:
  - {name: Prometheus, orgId: 1}
  - {name: Tempo, orgId: 1}
  - {name: Loki, orgId: 1}
  - {name: Alertmanager, orgId: 1}

datasources:
  - name: Prometheus
    uid: webterm-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Tempo
    uid: webterm-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
  - name: Loki
    uid: webterm-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
  - name: Alertmanager
    uid: webterm-alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus
