"""
Django settings for web_ui project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from .auth import build_auth_settings
from .celery_settings import build_celery_settings
from .database import build_cache_settings, build_channel_settings, build_database_settings
from .plugin_marketplace import build_plugin_marketplace_settings
from .runtime_services import build_runtime_service_settings
from .security import build_security_settings

# Загрузка .env до чтения os.getenv (для POSTGRES_*, CELERY_* и т.д.)
try:
    from dotenv import load_dotenv

    load_dotenv(Path(__file__).resolve().parent.parent.parent / ".env")
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


_RENDER_EXTERNAL_URL = (os.getenv("RENDER_EXTERNAL_URL", "") or "").rstrip("/")
_RENDER_EXTERNAL_HOSTNAME = (os.getenv("RENDER_EXTERNAL_HOSTNAME", "") or "").strip()
_security_settings = build_security_settings(
    render_external_url=_RENDER_EXTERNAL_URL,
    render_external_hostname=_RENDER_EXTERNAL_HOSTNAME,
)
globals().update(_security_settings)
DEBUG = bool(_security_settings["DEBUG"])
SITE_URL = str(_security_settings["SITE_URL"])


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "corsheaders",
    "core_ui",
    "plugin_marketplace.apps.PluginMarketplaceConfig",
    "servers",
    "studio",
    "mars",
    "kubernetes_ops",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core_ui.auth_throttle.LoginBruteForceProtectionMiddleware",
    "core_ui.domain_auth.DomainAutoLoginMiddleware",
    "core_ui.middleware.RequestAuditMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core_ui.middleware.AdminRussianMiddleware",
    "core_ui.middleware.MobileDetectionMiddleware",
]

ROOT_URLCONF = "web_ui.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "core_ui" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core_ui.context_processors.app_permissions",
            ],
        },
    },
]

WSGI_APPLICATION = "web_ui.wsgi.application"
ASGI_APPLICATION = "web_ui.asgi.application"

_channel_settings = build_channel_settings(debug=DEBUG)
globals().update(_channel_settings)
globals().update(build_cache_settings(redis_url=str(_channel_settings.get("CHANNEL_REDIS_URL") or "")))
globals().update(build_database_settings(base_dir=BASE_DIR))


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


globals().update(build_auth_settings(debug=DEBUG))
globals().update(build_plugin_marketplace_settings(debug=DEBUG))

# =============================================================================
# Email Configuration
# =============================================================================
# SMTP settings for sending emails (invitations, notifications, etc.)
# For development, use console backend. For production, configure SMTP.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "WebTerm <noreply@localhost>")

# Site URL for email links and approval callbacks
SITE_URL = SITE_URL or (_RENDER_EXTERNAL_URL or "http://localhost:9000")

# =============================================================================
# Pipeline Notifications — global defaults (used when nodes don't override)
# =============================================================================
# Who receives pipeline notifications (approvals, reports, alerts)
PIPELINE_NOTIFY_EMAIL = os.getenv("PIPELINE_NOTIFY_EMAIL", EMAIL_HOST_USER)

# Telegram Bot — used by output/telegram and logic/human_approval nodes globally
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "core_ui" / "static",
]

# Media files (uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
UPLOADED_FILES_DIR = MEDIA_ROOT / "uploads"
# Playbook project archives are authorization-protected source artifacts, not
# public media. Keep the default outside MEDIA_ROOT so neither Django's DEBUG
# media route nor the production nginx media alias can serve the raw bundle.
_PLAYBOOK_BUNDLE_STORAGE_ROOT = (os.getenv("PLAYBOOK_BUNDLE_STORAGE_ROOT", "") or "").strip()
PLAYBOOK_BUNDLE_STORAGE_ROOT = (
    Path(_PLAYBOOK_BUNDLE_STORAGE_ROOT) if _PLAYBOOK_BUNDLE_STORAGE_ROOT else BASE_DIR / "private" / "playbook_bundles"
)
PLAYBOOK_GITLAB_ALLOWED_HOSTS = tuple(
    host.strip().casefold()
    for host in (os.getenv("PLAYBOOK_GITLAB_ALLOWED_HOSTS", "gitlab.com") or "gitlab.com").split(",")
    if host.strip()
)
try:
    PLAYBOOK_GITLAB_TIMEOUT_SECONDS = max(1.0, float(os.getenv("PLAYBOOK_GITLAB_TIMEOUT_SECONDS", "15") or "15"))
except (TypeError, ValueError):
    PLAYBOOK_GITLAB_TIMEOUT_SECONDS = 15.0
SSH_PRIVATE_KEYS_DIR = BASE_DIR / "data" / "ssh_keys"

# Create upload directory if it doesn't exist
UPLOADED_FILES_DIR.mkdir(parents=True, exist_ok=True)

# Agent projects directory
AGENT_PROJECTS_DIR = BASE_DIR / "agent_projects"
AGENT_PROJECTS_DIR.mkdir(parents=True, exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # spool larger uploads to disk
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # reject oversized JSON/form bodies

globals().update(
    build_runtime_service_settings(
        base_dir=BASE_DIR,
        agent_projects_dir=AGENT_PROJECTS_DIR,
    )
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

globals().update(build_celery_settings(debug=DEBUG, time_zone=TIME_ZONE))
