# Generated by Django 6.0.5 on 2026-06-29 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sFleetBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=240)),
                ('target', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('rolling', 'Rolling'), ('degraded', 'Degraded'), ('paused', 'Paused'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('ready', models.PositiveIntegerField(default=0)),
                ('desired', models.PositiveIntegerField(default=0)),
                ('partitions', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='k8s_fleet_bundle_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='K8sProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('rancher', 'Rancher'), ('devtron', 'Devtron')], max_length=30)),
                ('base_url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
                ('auth_mode', models.CharField(choices=[('none', 'None'), ('secret_ref', 'Secret reference'), ('oidc', 'OIDC')], default='secret_ref', max_length=30)),
                ('secret_ref', models.CharField(blank=True, default='', max_length=200)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'enabled'], name='k8s_provider_kind_enabled_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='k8s_provider_kind_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('environment', models.CharField(blank=True, default='', max_length=50)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('rancher_cluster_id', models.CharField(blank=True, default='', max_length=160)),
                ('devtron_cluster_id', models.CharField(blank=True, default='', max_length=160)),
                ('nodes_ready', models.PositiveIntegerField(default=0)),
                ('nodes_total', models.PositiveIntegerField(default=0)),
                ('namespace_count', models.PositiveIntegerField(default=0)),
                ('workload_count', models.PositiveIntegerField(default=0)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rancher_provider', models.ForeignKey(blank=True, limit_choices_to={'kind': 'rancher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rancher_clusters', to='kubernetes_ops.k8sprovider')),
            ],
            options={
                'ordering': ['environment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='K8sAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=120)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kubernetes_ops.k8scluster')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='k8s_audit_action_created_idx'), models.Index(fields=['user', '-created_at'], name='k8s_audit_user_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='K8sAppRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('namespace', models.CharField(max_length=120)),
                ('environment', models.CharField(blank=True, default='', max_length=50)),
                ('owner', models.CharField(choices=[('fleet', 'Fleet'), ('devtron', 'Devtron'), ('external', 'External')], max_length=30)),
                ('team', models.CharField(blank=True, default='', max_length=120)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='kubernetes_ops.k8scluster')),
            ],
            options={
                'ordering': ['cluster__name', 'namespace', 'name'],
                'indexes': [models.Index(fields=['owner', 'health'], name='k8s_app_owner_health_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'namespace', 'name'), name='k8s_app_cluster_ns_name_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='k8scluster',
            index=models.Index(fields=['environment', 'health'], name='k8s_cluster_env_health_idx'),
        ),
        migrations.AddIndex(
            model_name='k8scluster',
            index=models.Index(fields=['rancher_cluster_id'], name='k8s_cluster_rancher_id_idx'),
        ),
    ]
