# Generated by Django 6.0.5 on 2026-06-29 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('environment', models.CharField(blank=True, default='', max_length=50)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('app_count', models.PositiveIntegerField(default=0)),
                ('workload_count', models.PositiveIntegerField(default=0)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces_inventory', to='kubernetes_ops.k8scluster')),
            ],
            options={
                'ordering': ['cluster__name', 'name'],
                'indexes': [models.Index(fields=['health'], name='k8s_namespace_health_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'name'), name='k8s_namespace_cluster_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='K8sWorkloadRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('deployment', 'Deployment'), ('statefulset', 'StatefulSet'), ('daemonset', 'DaemonSet'), ('cronjob', 'CronJob'), ('job', 'Job'), ('pod', 'Pod'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('environment', models.CharField(blank=True, default='', max_length=50)),
                ('owner', models.CharField(blank=True, default='rancher', max_length=60)),
                ('team', models.CharField(blank=True, default='', max_length=120)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('ready', models.PositiveIntegerField(default=0)),
                ('desired', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_refs', to='kubernetes_ops.k8scluster')),
            ],
            options={
                'ordering': ['cluster__name', 'namespace', 'kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'health'], name='k8s_workload_kind_health_idx'), models.Index(fields=['namespace'], name='k8s_workload_namespace_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'namespace', 'kind', 'name'), name='k8s_workload_cluster_ns_kind_name_unique')],
            },
        ),
    ]
