# Generated by Django 6.0.5 on 2026-06-29 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_ops', '0002_k8snamespace_k8sworkloadref'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uid', models.CharField(max_length=200)),
                ('source', models.CharField(default='rancher', max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField(blank=True, default='')),
                ('namespace', models.CharField(blank=True, default='', max_length=120)),
                ('involved_kind', models.CharField(blank=True, default='', max_length=80)),
                ('involved_name', models.CharField(blank=True, default='', max_length=180)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kubernetes_ops.k8scluster')),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['severity', '-last_seen_at'], name='k8s_event_severity_seen_idx'), models.Index(fields=['namespace'], name='k8s_event_namespace_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'event_uid'), name='k8s_event_cluster_uid_unique')],
            },
        ),
    ]
