# Generated by Django 6.0.5 on 2026-06-29 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_ops', '0003_k8sevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sNetworkRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('ingress', 'Ingress')], max_length=30)),
                ('environment', models.CharField(blank=True, default='', max_length=50)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('service_type', models.CharField(blank=True, default='', max_length=80)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('hosts', models.JSONField(blank=True, default=list)),
                ('endpoints', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_refs', to='kubernetes_ops.k8scluster')),
            ],
            options={
                'ordering': ['cluster__name', 'namespace', 'kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'health'], name='k8s_network_kind_health_idx'), models.Index(fields=['namespace'], name='k8s_network_namespace_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'namespace', 'kind', 'name'), name='k8s_network_cluster_ns_kind_name_unique')],
            },
        ),
    ]
