# Generated by Django 6.0.5 on 2026-06-29 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_ops', '0004_k8snetworkref'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sPodRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('environment', models.CharField(blank=True, default='', max_length=50)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('phase', models.CharField(blank=True, default='', max_length=80)),
                ('node_name', models.CharField(blank=True, default='', max_length=180)),
                ('pod_ip', models.CharField(blank=True, default='', max_length=80)),
                ('host_ip', models.CharField(blank=True, default='', max_length=80)),
                ('owner_kind', models.CharField(blank=True, default='', max_length=80)),
                ('owner_name', models.CharField(blank=True, default='', max_length=180)),
                ('ready_containers', models.PositiveIntegerField(default=0)),
                ('total_containers', models.PositiveIntegerField(default=0)),
                ('restart_count', models.PositiveIntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_refs', to='kubernetes_ops.k8scluster')),
            ],
            options={
                'ordering': ['cluster__name', 'namespace', 'name'],
                'indexes': [models.Index(fields=['health'], name='k8s_pod_health_idx'), models.Index(fields=['namespace'], name='k8s_pod_namespace_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'namespace', 'name'), name='k8s_pod_cluster_ns_name_unique')],
            },
        ),
    ]
