# Generated by Django 6.0.5 on 2026-06-30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kubernetes_ops", "0005_k8spodref"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="K8sActionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("username_snapshot", models.CharField(blank=True, default="", max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("k8s.rollout.restart", "Kubernetes rollout restart"),
                            ("fleet.rollout.pause", "Fleet rollout pause"),
                            ("fleet.rollout.resume", "Fleet rollout resume"),
                            ("gitops.create_merge_request", "GitOps merge request"),
                            ("devtron.open_rollback", "Devtron rollback deep link"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("execution_blocked", "Execution blocked"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_approval",
                        max_length=30,
                    ),
                ),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("target", models.JSONField(blank=True, default=dict)),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("execution_policy", models.JSONField(blank=True, default=dict)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True, default="")),
                ("approval_ref", models.CharField(blank=True, default="", max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kubernetes_ops.k8scluster",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kubernetes_action_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="k8s_action_status_created_idx"),
                    models.Index(fields=["action", "-created_at"], name="k8s_action_action_created_idx"),
                    models.Index(fields=["request_id"], name="k8s_action_reqid_idx"),
                ],
            },
        ),
    ]
