# Generated by Django 5.2.15 on 2026-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_ops', '0006_k8sactionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8sactionrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('execution_blocked', 'Execution blocked'), ('verified_external', 'Verified external execution'), ('verification_failed', 'External verification failed'), ('rejected', 'Rejected')], default='pending_approval', max_length=30),
        ),
    ]
