# Generated by Codex on 2026-07-01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kubernetes_ops", "0008_alter_k8sactionrequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="K8sAdminSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("username_snapshot", models.CharField(blank=True, default="", max_length=150)),
                ("namespace", models.CharField(blank=True, default="", max_length=120)),
                (
                    "mode",
                    models.CharField(
                        choices=[("read", "Read"), ("write", "Write"), ("break_glass", "Break glass")],
                        default="read",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("closed", "Closed"),
                        ],
                        default="pending_approval",
                        max_length=30,
                    ),
                ),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[("low", "Low"), ("high", "High"), ("critical", "Critical")],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("approval_ref", models.CharField(blank=True, default="", max_length=160)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("allowed_verbs", models.JSONField(blank=True, default=list)),
                ("allowed_kinds", models.JSONField(blank=True, default=list)),
                ("allowed_namespaces", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_kubernetes_admin_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_sessions",
                        to="kubernetes_ops.k8scluster",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_sessions",
                        to="kubernetes_ops.k8sprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kubernetes_admin_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="k8s_admin_s_status_exp_idx"),
                    models.Index(fields=["user", "status"], name="k8s_admin_s_user_status_idx"),
                    models.Index(fields=["mode", "status"], name="k8s_admin_s_mode_status_idx"),
                    models.Index(fields=["cluster", "namespace"], name="k8s_admin_s_cluster_ns_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="K8sAdminAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("username_snapshot", models.CharField(blank=True, default="", max_length=150)),
                ("namespace", models.CharField(blank=True, default="", max_length=120)),
                ("resource_api_version", models.CharField(blank=True, default="", max_length=80)),
                ("resource_kind", models.CharField(blank=True, default="", max_length=80)),
                ("resource_name", models.CharField(blank=True, default="", max_length=180)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("get", "Get"),
                            ("list", "List"),
                            ("watch", "Watch"),
                            ("logs", "Logs"),
                            ("yaml", "YAML"),
                            ("dry_run_apply", "Dry-run apply"),
                            ("apply", "Apply"),
                            ("patch", "Patch"),
                            ("scale", "Scale"),
                            ("restart", "Restart"),
                            ("delete", "Delete"),
                            ("exec", "Exec"),
                            ("port_forward", "Port forward"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("dry_run", "Dry run"),
                            ("execution_blocked", "Execution blocked"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=30,
                    ),
                ),
                ("request_payload_sanitized", models.JSONField(blank=True, default=dict)),
                ("diff_summary", models.JSONField(blank=True, default=dict)),
                ("response_summary", models.JSONField(blank=True, default=dict)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to="kubernetes_ops.k8scluster",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="kubernetes_ops.k8sadminsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kubernetes_admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["session", "-created_at"], name="k8s_admin_a_session_idx"),
                    models.Index(fields=["verb", "status"], name="k8s_admin_a_verb_status_idx"),
                    models.Index(fields=["cluster", "namespace"], name="k8s_admin_a_cluster_ns_idx"),
                ],
            },
        ),
    ]
