# Generated by Codex on 2026-07-01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kubernetes_ops", "0009_k8sadminsession_k8sadminaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="k8sadminaction",
            name="verb",
            field=models.CharField(
                choices=[
                    ("get", "Get"),
                    ("list", "List"),
                    ("watch", "Watch"),
                    ("logs", "Logs"),
                    ("yaml", "YAML"),
                    ("dry_run_apply", "Dry-run apply"),
                    ("apply", "Apply"),
                    ("patch", "Patch"),
                    ("scale", "Scale"),
                    ("restart", "Restart"),
                    ("delete", "Delete"),
                    ("exec", "Exec"),
                    ("port_forward", "Port forward"),
                    ("cluster_terminal", "Cluster terminal"),
                    ("node_debug", "Node debug"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="K8sAdminRecording",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recording_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("username_snapshot", models.CharField(blank=True, default="", max_length=150)),
                ("namespace", models.CharField(blank=True, default="", max_length=120)),
                ("resource_kind", models.CharField(blank=True, default="", max_length=80)),
                ("resource_name", models.CharField(blank=True, default="", max_length=180)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("exec", "Exec"),
                            ("port_forward", "Port forward"),
                            ("cluster_terminal", "Cluster terminal"),
                            ("node_debug", "Node debug"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("blocked", "Blocked"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("mode", models.CharField(blank=True, default="metadata_only", max_length=40)),
                ("transcript_required", models.BooleanField(default=False)),
                ("transcript_stored", models.BooleanField(default=False)),
                ("payload_stored", models.BooleanField(default=False)),
                ("stdin_recording_required", models.BooleanField(default=False)),
                ("stdout_recording_required", models.BooleanField(default=False)),
                ("metadata_retention_days", models.PositiveIntegerField(default=365)),
                ("transcript_retention_days", models.PositiveIntegerField(default=30)),
                ("metadata_delete_after", models.DateTimeField(blank=True, null=True)),
                ("transcript_delete_after", models.DateTimeField(blank=True, null=True)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to="kubernetes_ops.k8sadminaction",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_recordings",
                        to="kubernetes_ops.k8scluster",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="kubernetes_ops.k8sadminsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kubernetes_admin_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["session", "-created_at"], name="k8s_admin_r_session_idx"),
                    models.Index(fields=["action", "operation"], name="k8s_admin_r_action_op_idx"),
                    models.Index(fields=["operation", "status"], name="k8s_admin_r_op_status_idx"),
                    models.Index(fields=["metadata_delete_after"], name="k8s_admin_r_meta_del_idx"),
                ],
            },
        ),
    ]
