# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kubernetes_ops", "0010_k8sadminrecording"),
    ]

    operations = [
        migrations.CreateModel(
            name="K8sAdminRecordingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("stdin", "stdin"),
                            ("stdout", "stdout"),
                            ("stderr", "stderr"),
                            ("status", "status"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.TextField(blank=True, default="")),
                ("original_length", models.PositiveIntegerField(default=0)),
                ("stored_length", models.PositiveIntegerField(default=0)),
                ("redacted", models.BooleanField(default=False)),
                ("truncated", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="kubernetes_ops.k8sadminrecording",
                    ),
                ),
            ],
            options={
                "ordering": ["recording", "sequence", "id"],
                "indexes": [
                    models.Index(fields=["recording", "sequence"], name="k8s_admin_re_rec_seq_idx"),
                    models.Index(fields=["stream", "created_at"], name="k8s_admin_re_stream_idx"),
                ],
            },
        ),
    ]
