# Generated by Django 5.2.15 on 2026-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_ops', '0011_k8sadminrecordingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8sadminaction',
            name='verb',
            field=models.CharField(choices=[('get', 'Get'), ('list', 'List'), ('watch', 'Watch'), ('logs', 'Logs'), ('yaml', 'YAML'), ('dry_run_apply', 'Dry-run apply'), ('apply', 'Apply'), ('patch', 'Patch'), ('scale', 'Scale'), ('restart', 'Restart'), ('delete', 'Delete'), ('cordon', 'Cordon'), ('uncordon', 'Uncordon'), ('drain', 'Drain'), ('exec', 'Exec'), ('port_forward', 'Port forward'), ('cluster_terminal', 'Cluster terminal'), ('node_debug', 'Node debug')], max_length=30),
        ),
    ]
