# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kubernetes_ops", "0013_alter_k8sactionrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="k8sactionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending approval"),
                    ("approved_external", "Approved for external execution"),
                    ("executed_native", "Executed natively by WebTerm"),
                    ("execution_blocked", "Execution blocked"),
                    ("verified_external", "Verified external execution"),
                    ("verified_native", "Verified native execution"),
                    ("verification_failed", "Action verification failed"),
                    ("rejected", "Rejected"),
                ],
                default="pending_approval",
                max_length=30,
            ),
        ),
    ]
