# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kubernetes_ops", "0014_alter_k8sactionrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="k8sactionrequest",
            name="action",
            field=models.CharField(
                choices=[
                    ("k8s.rollout.restart", "Kubernetes rollout restart"),
                    ("k8s.workload.scale", "Kubernetes workload scale"),
                    ("fleet.rollout.pause", "Fleet rollout pause"),
                    ("fleet.rollout.resume", "Fleet rollout resume"),
                    ("gitops.create_merge_request", "GitOps merge request"),
                    ("devtron.open_rollback", "Devtron rollback deep link"),
                ],
                max_length=80,
            ),
        ),
    ]
