# Generated by Django 6.0.7 on 2026-09-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes_ops', '0019_k8sprovider_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='k8sprovider',
            name='scope',
            field=models.CharField(choices=[('personal', 'Personal'), ('platform', 'Platform')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='k8sprovider',
            name='base_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='k8sprovider',
            name='kind',
            field=models.CharField(choices=[('rancher', 'Rancher'), ('devtron', 'Devtron'), ('kubeconfig', 'Kubeconfig')], max_length=30),
        ),
        migrations.CreateModel(
            name='K8sClusterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespaces', models.JSONField(blank=True, default=list, help_text='Empty list = entire cluster (subject to kube RBAC). Non-empty = allow-list.')),
                ('can_view_logs', models.BooleanField(default=True)),
                ('can_exec', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='kubernetes_ops.k8scluster')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k8s_cluster_access_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k8s_cluster_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='k8s_access_user_revoked_idx'), models.Index(fields=['cluster', 'is_revoked'], name='k8s_access_cluster_revoked_idx'), models.Index(fields=['expires_at'], name='k8s_access_expires_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'user'), name='k8s_cluster_access_cluster_user_unique')],
            },
        ),
    ]
