# Generated by Django 5.2.10 on 2026-03-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core_ui", "0007_rename_core_ui_des_user_id_9664d3_idx_core_ui_des_user_id_ae5a41_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupAppPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("servers", "Servers"),
                            ("dashboard", "Dashboard"),
                            ("agents", "Agents"),
                            ("studio", "Studio"),
                            ("settings", "Settings"),
                            ("orchestrator", "Orchestrator"),
                            ("knowledge_base", "Knowledge Base"),
                        ],
                        max_length=30,
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_permissions",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "feature"],
                "indexes": [models.Index(fields=["group", "feature"], name="core_ui_gro_group_i_a5ba41_idx")],
                "unique_together": {("group", "feature")},
            },
        ),
    ]
