# Generated by Django 5.2.10 on 2026-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0008_groupapppermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapppermission',
            name='feature',
            field=models.CharField(choices=[('servers', 'Servers'), ('dashboard', 'Dashboard'), ('agents', 'Agents'), ('studio', 'Studio'), ('studio_pipelines', 'Studio Pipelines'), ('studio_runs', 'Studio Runs'), ('studio_agents', 'Studio Agents'), ('studio_skills', 'Studio Skills'), ('studio_mcp', 'Studio MCP'), ('studio_notifications', 'Studio Notifications'), ('settings', 'Settings'), ('orchestrator', 'Orchestrator'), ('knowledge_base', 'Knowledge Base')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userapppermission',
            name='feature',
            field=models.CharField(choices=[('servers', 'Servers'), ('dashboard', 'Dashboard'), ('agents', 'Agents'), ('studio', 'Studio'), ('studio_pipelines', 'Studio Pipelines'), ('studio_runs', 'Studio Runs'), ('studio_agents', 'Studio Agents'), ('studio_skills', 'Studio Skills'), ('studio_mcp', 'Studio MCP'), ('studio_notifications', 'Studio Notifications'), ('settings', 'Settings'), ('orchestrator', 'Orchestrator'), ('knowledge_base', 'Knowledge Base')], max_length=30),
        ),
    ]
