# Generated by Django 5.2.10 on 2026-04-16 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0010_add_missing_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(default='one_dark', max_length=40)),
                ('theme_colors', models.JSONField(blank=True, default=dict)),
                ('font_size', models.PositiveSmallIntegerField(default=14)),
                ('font_family', models.CharField(default='JetBrains Mono', max_length=80)),
                ('line_height', models.FloatField(default=1.4)),
                ('cursor_style', models.CharField(choices=[('block', 'Block'), ('bar', 'Bar'), ('underline', 'Underline')], default='block', max_length=10)),
                ('cursor_blink', models.BooleanField(default=True)),
                ('scrollback', models.PositiveIntegerField(default=5000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='core_ui_ter_user_id_31b7e8_idx')],
            },
        ),
    ]
