# Generated by Django 5.2.10 on 2026-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0011_add_terminal_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalpreference',
            name='intercept_editors',
            field=models.BooleanField(default=True),
        ),
    ]
