# Generated by Django 5.2.10 on 2026-05-20 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0012_add_intercept_editors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_type', models.CharField(choices=[('admin', 'Admin Dashboard'), ('user', 'User Dashboard')], max_length=20)),
                ('layout_data', models.JSONField(default=dict, help_text='JSON mapping of widget IDs to their grid positions and sizes.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'dashboard_type'], name='core_ui_das_user_id_1d8ddc_idx')],
                'unique_together': {('user', 'dashboard_type')},
            },
        ),
    ]
