# Generated by Django 6.0.5 on 2026-06-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0014_add_mars_kubernetes_features'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='desktoprefreshtoken',
            name='core_ui_des_user_id_ae5a41_idx',
        ),
        migrations.RemoveIndex(
            model_name='desktoprefreshtoken',
            name='core_ui_des_expires_697b0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='desktoprefreshtoken',
            name='core_ui_des_revoked_39c67f_idx',
        ),
        migrations.DeleteModel(
            name='DesktopRefreshToken',
        ),
    ]
