# Generated by Codex on 2026-06-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_ui", "0015_remove_desktoprefreshtoken_core_ui_des_user_id_ae5a41_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AssistantAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(max_length=120)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("requires_confirmation", "Requires confirmation"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=30,
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("internal_write", "Internal write"),
                            ("external", "External"),
                            ("mutating", "Mutating"),
                            ("dangerous", "Dangerous"),
                        ],
                        default="read",
                        max_length=30,
                    ),
                ),
                ("required_feature", models.CharField(blank=True, default="", max_length=40)),
                ("requires_confirmation", models.BooleanField(default=False)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("safe_preview", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("target_url", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="core_ui.chatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="core_ui.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="cu_asst_user_created_idx"),
                    models.Index(fields=["session", "created_at"], name="cu_asst_session_created_idx"),
                    models.Index(fields=["status", "-updated_at"], name="cu_asst_status_updated_idx"),
                    models.Index(fields=["action_type"], name="cu_asst_type_idx"),
                ],
            },
        ),
    ]
