# Generated by Django 6.0.7 on 2026-07-20 23:24

from django.db import migrations, models


ACTIVE_STATUSES = ["running", "awaiting_confirm", "awaiting_async", "resuming"]


def close_duplicate_active_turns(apps, schema_editor):
    ChatTurnState = apps.get_model("core_ui", "ChatTurnState")
    session_ids = (
        ChatTurnState.objects.filter(status__in=ACTIVE_STATUSES)
        .values_list("session_id", flat=True)
        .distinct()
    )
    for session_id in session_ids.iterator():
        ids = list(
            ChatTurnState.objects.filter(session_id=session_id, status__in=ACTIVE_STATUSES)
            .order_by("-updated_at", "-id")
            .values_list("id", flat=True)
        )
        if len(ids) > 1:
            ChatTurnState.objects.filter(id__in=ids[1:]).update(
                status="failed",
                error="superseded_before_active_turn_constraint",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0020_chatturnstate_awaiting_async'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapppermission',
            name='feature',
            field=models.CharField(choices=[('servers', 'Servers'), ('dashboard', 'Dashboard'), ('agents', 'Agents'), ('studio', 'Studio'), ('studio_pipelines', 'Studio Pipelines'), ('studio_runs', 'Studio Runs'), ('studio_agents', 'Studio Agents'), ('studio_skills', 'Studio Skills'), ('studio_mcp', 'Studio MCP'), ('studio_notifications', 'Studio Notifications'), ('kubernetes', 'Kubernetes'), ('kubernetes_admin_read', 'Kubernetes Admin Read'), ('kubernetes_admin_write', 'Kubernetes Admin Write'), ('kubernetes_break_glass', 'Kubernetes Break Glass'), ('kubernetes_secret_read', 'Kubernetes Secret Read'), ('mars', 'MARS'), ('settings', 'Settings'), ('orchestrator', 'Orchestrator'), ('knowledge_base', 'Knowledge Base'), ('web_research', 'Web Research')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userapppermission',
            name='feature',
            field=models.CharField(choices=[('servers', 'Servers'), ('dashboard', 'Dashboard'), ('agents', 'Agents'), ('studio', 'Studio'), ('studio_pipelines', 'Studio Pipelines'), ('studio_runs', 'Studio Runs'), ('studio_agents', 'Studio Agents'), ('studio_skills', 'Studio Skills'), ('studio_mcp', 'Studio MCP'), ('studio_notifications', 'Studio Notifications'), ('kubernetes', 'Kubernetes'), ('kubernetes_admin_read', 'Kubernetes Admin Read'), ('kubernetes_admin_write', 'Kubernetes Admin Write'), ('kubernetes_break_glass', 'Kubernetes Break Glass'), ('kubernetes_secret_read', 'Kubernetes Secret Read'), ('mars', 'MARS'), ('settings', 'Settings'), ('orchestrator', 'Orchestrator'), ('knowledge_base', 'Knowledge Base'), ('web_research', 'Web Research')], max_length=30),
        ),
        migrations.RunPython(close_duplicate_active_turns, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='chatturnstate',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['running', 'awaiting_confirm', 'awaiting_async', 'resuming'])), fields=('session',), name='cu_turn_one_active_per_session'),
        ),
    ]
