# Generated by Django 6.0.7 on 2026-07-30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_personal_projects(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Project = apps.get_model("core_ui", "Project")
    ProjectMembership = apps.get_model("core_ui", "ProjectMembership")
    for user in User.objects.all().iterator(chunk_size=500):
        project = Project.objects.create(
            public_id=uuid.uuid4(),
            name=f"{user.username}'s project"[:120],
            slug=f"personal-{user.id}",
            owner_id=user.id,
            is_default=True,
        )
        ProjectMembership.objects.create(
            project_id=project.id,
            user_id=user.id,
            role="owner",
            is_active=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core_ui", "0021_alter_groupapppermission_feature_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [models.Index(fields=["owner", "is_archived"], name="core_ui_pr_owner_i_553ce9_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("owner",),
                        name="core_one_default_project_per_owner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("admin", "Admin"), ("operator", "Operator"), ("viewer", "Viewer")],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core_ui.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project", "user"],
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="core_ui_pr_user_id_81b66d_idx"),
                    models.Index(fields=["project", "role"], name="core_ui_pr_project_66f2e2_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("project", "user"), name="core_unique_project_member"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("user",),
                        name="core_one_active_project_per_user",
                    ),
                ],
            },
        ),
        migrations.RunPython(create_personal_projects, migrations.RunPython.noop),
    ]
