# Generated by Django 5.2.16 on 2026-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0023_operatorturndispatch'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatartifact',
            index=models.Index(fields=['created_at'], name='cu_art_created_idx'),
        ),
    ]
