# Generated by Django 5.2.10 on 2026-08-10 23:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core_ui', '0024_chatartifact_cu_art_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_id', models.CharField(choices=[('codex_subscription', 'Codex subscription'), ('grok_subscription', 'Grok subscription')], max_length=64)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('workspace', 'Workspace')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('credential_ref', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending_auth', 'Pending authentication'), ('connected', 'Connected'), ('auth_required', 'Authentication required'), ('limited', 'Limited'), ('degraded', 'Degraded'), ('disabled', 'Disabled'), ('revoked', 'Revoked')], default='pending_auth', max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('runtime_version', models.CharField(blank=True, default='', max_length=80)),
                ('auth_revision', models.PositiveIntegerField(default=0)),
                ('concurrency_limit', models.PositiveSmallIntegerField(default=1)),
                ('health', models.JSONField(blank=True, default=dict)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_provider_connections', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIConnectionAuthFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flow_kind', models.CharField(default='device_code', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verification_uri', models.URLField(blank=True, default='', max_length=500)),
                ('user_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_flows', to='core_ui.aiproviderconnection')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderConnectionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(blank=True, default='', max_length=20)),
                ('allow_interactive', models.BooleanField(default=True)),
                ('allow_unattended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core_ui.aiproviderconnection')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_grants', to='auth.group')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_connection_grants', to='core_ui.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_connection_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIProviderInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_id', models.CharField(choices=[('openai_api', 'openai_api'), ('grok_api', 'grok_api'), ('claude_api', 'claude_api'), ('gemini_api', 'gemini_api'), ('ollama_local', 'ollama_local'), ('codex_subscription', 'codex_subscription'), ('grok_subscription', 'grok_subscription')], max_length=64)),
                ('purpose', models.CharField(max_length=40)),
                ('source_kind', models.CharField(max_length=60)),
                ('source_id', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('interactive', 'interactive'), ('unattended', 'unattended')], max_length=20)),
                ('binding_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('auth_required', 'Authentication required'), ('limit', 'Limit')], default='queued', max_length=24)),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=160)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocations', to='core_ui.aiproviderconnection')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_provider_invocations', to='core_ui.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_provider_invocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(default=1)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fencing_token', models.PositiveBigIntegerField(default=1)),
                ('owner_id', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core_ui.aiproviderconnection')),
                ('invocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core_ui.aiproviderinvocation')),
            ],
        ),
        migrations.CreateModel(
            name='AIProviderPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('target_id', models.CharField(choices=[('codex_subscription', 'Codex subscription'), ('grok_subscription', 'Grok subscription')], max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_provider_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='aiproviderinvocation',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invocations', to='core_ui.aiproviderpool'),
        ),
        migrations.CreateModel(
            name='AIProviderPoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='core_ui.aiproviderconnection')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core_ui.aiproviderpool')),
            ],
        ),
        migrations.CreateModel(
            name='AIProviderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('assistant', 'Assistant'), ('agents', 'Agents'), ('terminal', 'Terminal'), ('internal', 'Internal')], max_length=20)),
                ('target_id', models.CharField(choices=[('openai_api', 'openai_api'), ('grok_api', 'grok_api'), ('claude_api', 'claude_api'), ('gemini_api', 'gemini_api'), ('ollama_local', 'ollama_local'), ('codex_subscription', 'codex_subscription'), ('grok_subscription', 'grok_subscription')], max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core_ui.aiproviderconnection')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core_ui.aiproviderpool')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_preferences', to='core_ui.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='aiproviderconnection',
            index=models.Index(fields=['owner', 'enabled', 'status'], name='cu_ai_conn_owner_status'),
        ),
        migrations.AddIndex(
            model_name='aiproviderconnection',
            index=models.Index(fields=['scope', 'target_id', 'enabled'], name='cu_ai_conn_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('scope', 'personal')), models.Q(('owner__isnull', True), ('scope', 'workspace')), _connector='OR'), name='cu_ai_conn_scope_owner'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconnection',
            constraint=models.CheckConstraint(condition=models.Q(('concurrency_limit__gte', 1)), name='cu_ai_conn_concurrency_gte1'),
        ),
        migrations.AddConstraint(
            model_name='aiconnectionauthflow',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('connection',), name='cu_ai_auth_one_pending_conn'),
        ),
        migrations.AddIndex(
            model_name='aiproviderconnectiongrant',
            index=models.Index(fields=['connection', 'project'], name='cu_ai_grant_conn_project'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconnectiongrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('project__isnull', True), ('project_role', ''), ('user__isnull', False)), models.Q(('group__isnull', False), ('project__isnull', True), ('project_role', ''), ('user__isnull', True)), models.Q(('group__isnull', True), ('project__isnull', False), ('user__isnull', True)), _connector='OR'), name='cu_ai_grant_one_principal'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconnectiongrant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('connection', 'user'), name='cu_ai_grant_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconnectiongrant',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('connection', 'group'), name='cu_ai_grant_unique_group'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderconnectiongrant',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('connection', 'project', 'project_role'), name='cu_ai_grant_unique_project_role'),
        ),
        migrations.AddIndex(
            model_name='aiproviderlease',
            index=models.Index(fields=['status', 'expires_at'], name='cu_ai_lease_status_exp'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderlease',
            constraint=models.CheckConstraint(condition=models.Q(('slot__gte', 1)), name='cu_ai_lease_slot_gte1'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderlease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('invocation',), name='cu_ai_lease_one_active_inv'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderlease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('connection', 'slot'), name='cu_ai_lease_unique_active_slot'),
        ),
        migrations.AddIndex(
            model_name='aiproviderinvocation',
            index=models.Index(fields=['user', '-created_at'], name='cu_ai_inv_user_created'),
        ),
        migrations.AddIndex(
            model_name='aiproviderinvocation',
            index=models.Index(fields=['status', 'created_at'], name='cu_ai_inv_status_created'),
        ),
        migrations.AddIndex(
            model_name='aiproviderinvocation',
            index=models.Index(fields=['source_kind', 'source_id'], name='cu_ai_inv_source'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderinvocation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='cu_ai_invocation_idempotent'),
        ),
        migrations.AddIndex(
            model_name='aiproviderpoolmember',
            index=models.Index(fields=['pool', 'enabled'], name='cu_ai_pool_member_enabled'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderpoolmember',
            constraint=models.UniqueConstraint(fields=('pool', 'connection'), name='cu_ai_pool_unique_member'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderpoolmember',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 1)), name='cu_ai_pool_weight_gte1'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderpreference',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('project__isnull', False), ('user__isnull', True)), _connector='OR'), name='cu_ai_pref_user_or_workspace'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderpreference',
            constraint=models.CheckConstraint(condition=models.Q(('connection__isnull', True), ('pool__isnull', True), _connector='OR'), name='cu_ai_pref_not_conn_and_pool'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False), ('user__isnull', False)), fields=('user', 'project', 'purpose'), name='cu_ai_pref_unique_user_project'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True), ('user__isnull', False)), fields=('user', 'purpose'), name='cu_ai_pref_unique_user_global'),
        ),
        migrations.AddConstraint(
            model_name='aiproviderpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False), ('user__isnull', True)), fields=('project', 'purpose'), name='cu_ai_pref_unique_workspace'),
        ),
    ]
