# Generated by Django 5.2.10 on 2026-08-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0025_aiproviderconnection_aiconnectionauthflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='provider_binding',
            field=models.JSONField(blank=True, default=dict, help_text='Pinned canonical AI provider binding for this chat session.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='provider_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatturnstate',
            name='provider_binding_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatturnstate',
            name='provider_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
