# Generated by Django 5.2.10 on 2026-08-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0026_chatsession_provider_binding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconnectionauthflow',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconnectionauthflow',
            name='claimed_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aiconnectionauthflow',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
