# Generated by Django 5.2.10 on 2026-09-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_ui', '0030_usernotificationpreference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotificationpreference',
            new_name='core_ui_use_user_id_fbb06a_idx',
            old_name='core_ui_use_user_id_notif_idx',
        ),
    ]
