"""Port contracts for the agent_kernel memory subsystem.

Consumers of the memory layer (e.g. app.agent_kernel) should import
abstractions from this module so they never depend on the concrete Django
implementation in store.py.
"""
from __future__ import annotations

from typing import Any, Protocol

from app.agent_kernel.domain.specs import ServerMemoryCard


class MemoryStore(Protocol):
    async def get_server_card(self, server_id: int) -> ServerMemoryCard: ...
    async def search_runbooks(self, query: str, *, server_id: int | None = None, group_id: int | None = None) -> list[dict]: ...
    async def build_operational_recipes_prompt(
        self,
        query: str,
        *,
        server_ids: list[int] | None = None,
        group_ids: list[int] | None = None,
        limit: int = 5,
    ) -> str: ...
    async def append_run_summary(self, run_id: int, summary: dict) -> str: ...
    async def upsert_server_fact(self, server_id: int, fact: dict) -> str: ...
    async def record_change(self, server_id: int, change: dict) -> str: ...
    async def record_incident(self, server_id: int, incident: dict) -> str: ...
    async def detect_conflicts(self, server_id: int, new_facts: list[dict]) -> list[dict]: ...
    async def repair_server_memory(self, server_id: int, *, stale_after_days: int = 30, create_notes: bool = True) -> dict: ...
    async def dream_server_memory(self, server_id: int, *, deactivate_noise: bool = True, job_kind: str = "hybrid") -> dict: ...
    async def archive_snapshot(self, server_id: int, snapshot_id: int, *, actor_user_id: int | None = None) -> dict[str, Any]: ...
    async def hard_delete_snapshot(self, server_id: int, snapshot_id: int, *, actor_user_id: int | None = None) -> dict[str, Any]: ...
    async def purge_server_ai_memory(self, server_id: int, *, actor_user_id: int | None = None) -> dict[str, Any]: ...
    async def promote_snapshot_to_manual_knowledge(
        self,
        server_id: int,
        snapshot_id: int,
        *,
        actor_user_id: int,
    ) -> dict[str, Any]: ...
    async def promote_skill_draft_to_skill(
        self,
        server_id: int,
        snapshot_id: int,
        *,
        actor_user_id: int,
    ) -> dict[str, Any]: ...
