from django.urls import path

from plugin_marketplace.views import (
    catalog_views,
    compatibility_views,
    connector_views,
    hook_views,
    install_views,
    lifecycle_views,
    package_views,
    permission_views,
    review_views,
    settings_views,
    surface_views,
    terminal_action_views,
)

app_name = "plugin_marketplace"

urlpatterns = [
    path("catalog/", install_views.catalog, name="catalog"),
    path("installed/", install_views.installed_plugins, name="installed"),
    path("installed/<int:installation_id>/scope/", install_views.installation_scope, name="scope"),
    path("installed/<int:installation_id>/scope/update/", install_views.update_scope, name="update_scope"),
    path("installed/<int:installation_id>/enable/", install_views.enable_plugin, name="enable"),
    path("installed/<int:installation_id>/disable/", install_views.disable_plugin, name="disable"),
    path("installed/<int:installation_id>/impact/", lifecycle_views.installation_impact_view, name="impact"),
    path("installed/<int:installation_id>/update-preview/", lifecycle_views.update_preview_view, name="update_preview"),
    path("installed/<int:installation_id>/update-package/", lifecycle_views.update_package_view, name="update_package"),
    path("installed/<int:installation_id>/soft-uninstall/", lifecycle_views.soft_uninstall_view, name="soft_uninstall"),
    path("installed/<int:installation_id>/rollback/", lifecycle_views.rollback_view, name="rollback"),
    path("installed/<int:installation_id>/permissions/", permission_views.installation_permissions, name="permissions"),
    path("installed/<int:installation_id>/permissions/grant/", permission_views.grant_plugin_permission, name="grant_permission"),
    path("installed/<int:installation_id>/permissions/revoke/", permission_views.revoke_plugin_permission, name="revoke_permission"),
    path("installed/<int:installation_id>/settings/", settings_views.plugin_settings, name="settings"),
    path("installed/<int:installation_id>/settings/update/", settings_views.update_plugin_settings, name="update_settings"),
    path("installed/<int:installation_id>/secrets/bind/", settings_views.bind_plugin_secret, name="bind_secret"),
    path("surfaces/", surface_views.active_surfaces, name="surfaces"),
    path("pages/<str:plugin_id>/<str:page_id>/", surface_views.plugin_page, name="plugin_page"),
    path("connectors/<str:plugin_id>/<str:connector_id>/health/", connector_views.connector_health_view, name="connector_health"),
    path("connectors/<str:plugin_id>/<str:connector_id>/ping/", connector_views.connector_ping_view, name="connector_ping"),
    path("terminal-actions/<str:plugin_id>/<str:action_id>/execute/", terminal_action_views.execute_terminal_action_view, name="terminal_action_execute"),
    path("hooks/emit/", hook_views.emit_hook_event_view, name="emit_hook"),
    path("packages/validate-path/", package_views.validate_package_path, name="validate_package_path"),
    path("packages/install-local-upload/", package_views.install_local_upload, name="install_local_upload"),
    path("packages/install-remote/", package_views.install_remote_package, name="install_remote_package"),
    path("packages/retention/", package_views.retention_view, name="package_retention"),
    path("review/packages/", review_views.review_packages, name="review_packages"),
    path("review/packages/<int:package_id>/review/", review_views.review_package, name="review_package"),
    path("review/packages/<int:package_id>/sign/", review_views.sign_package_view, name="sign_package"),
    path("review/packages/<int:package_id>/verify-signature/", review_views.verify_package_signature_view, name="verify_signature"),
    path("review/packages/<int:package_id>/attest/", review_views.attest_package_view, name="attest_package"),
    path("review/packages/<int:package_id>/security-scan/", review_views.security_scan_package_view, name="security_scan_package"),
    path("review/packages/<int:package_id>/replay-provenance/", review_views.replay_package_provenance_view, name="replay_provenance"),
    path("review/packages/<int:package_id>/sbom/", review_views.package_sbom_view, name="package_sbom"),
    path("marketplace/sources/", catalog_views.marketplace_sources, name="marketplace_sources"),
    path("marketplace/sources/<int:source_id>/", catalog_views.marketplace_source_detail, name="marketplace_source_detail"),
    path("marketplace/sources/<int:source_id>/sync/", catalog_views.marketplace_source_sync, name="marketplace_source_sync"),
    path("marketplace/sources/<int:source_id>/sync-remote/", catalog_views.marketplace_source_sync_remote, name="marketplace_source_sync_remote"),
    path("marketplace/catalog/", catalog_views.marketplace_catalog, name="marketplace_catalog"),
    path("marketplace/catalog/<int:item_id>/", catalog_views.marketplace_catalog_detail, name="marketplace_catalog_detail"),
    path("marketplace/catalog/<int:item_id>/install/", catalog_views.install_marketplace_item, name="marketplace_install"),
    path("marketplace/compatibility-matrix/", compatibility_views.compatibility_matrix, name="compatibility_matrix"),
    path("marketplace/compatibility-jobs/", compatibility_views.compatibility_jobs, name="compatibility_jobs"),
    path("quarantine/", lifecycle_views.quarantine_plugin_view, name="quarantine_plugin"),
    path("demo/action/", install_views.demo_action, name="demo_action"),
]
